---
sidebar: sidebar 
permalink: hu-aix-rn.html 
keywords: host utilities, aix, 6.1 netapp, 7.0, ontap, powervm 
summary: 《AIX Host Utilities 6.1发行说明》 
---
= 《AIX Host Utilities发行说明》
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本发行说明介绍了新功能和增强功能、当前版本中已修复的问题、已知问题和限制以及与使用ONTAP存储系统配置和管理特定AIX主机相关的重要注意事项。

有关Host Utilities支持的操作系统版本和更新的特定信息，请参阅link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]。



== 新增功能

AIX Host Utilities版本包含以下新增功能和增强功能：

* AIX Host Utilities 7.0支持AIX主机操作系统上的SCSI UNMAP。借助AIX Host Utilities 7.0、SCSI精简配置可与FC设备的AIX和NetApp LUN无缝配合使用。
* AIX Host Utilities 6.1支持在早期版本的AIX主机操作系统中发生的内存故障问题。在AIX Host Utilities 6.1中、只有sanlun二进制文件发生了更改。Microsoft多路径I/O (MPIO)和相关ODM保持不变。




== 已知问题和限制

您应了解以下已知问题和限制、这些问题和限制可能会影响特定主机的性能。

[cols="3"]
|===
| 错误 ID | 标题 | Description 


| 不适用 | ONTAP iSCSI LUN的SCSI UNMAP支持 | AIX Host Utilities 7.0仅支持FC设备的SCSI UNMAP功能。此版本不支持对iSCSI设备的SCSI UNMAP。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1069147["1069147"^] | AIX HU Sanlun报告的HBA速度不正确 | 运行`sanlun fcp show adapter–v`命令时、报告sanlun显示不正确的HBA速度的实例。`sanlun fcp show adapter–v`命令可显示HBA卡信息、例如适配器支持的速度和协商的速度。这似乎只是一个报告问题描述。要确定实际速度、请使用`fcstat fcsx`命令。 
|===
link:https://mysupport.netapp.com/site/["NetApp Bug Online"^] 提供有关大多数已知问题的完整信息、包括可能的建议解决方法。您可能需要使用的一些关键字组合和错误类型包括：

* FCP常规：显示与特定主机无关的FC和HBA错误。
* FCP—AIX

