---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: AIX统一主机实用程序可帮助您管理连接到AIX主机的NetApp ONTAP存储。 
---
= 安装AIX Host Utilities 7.0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX统一主机实用程序可帮助您管理连接到AIX主机的NetApp ONTAP存储。

AIX Host Utilities支持以下协议：

* FC
* FCoE
* iSCSI


AIX Host Utilities支持以下环境：

* AIX MPIO (本机操作系统)
* PowerVM
+
有关PowerVM的详细信息、请参见IBM PowerVM Live Partition Mobility红皮书。



.开始之前
* 为了确保操作可靠、请验证您的整个iSCSI、FC或FCoE配置是否受支持。
+
您可以使用 https://mysupport.netapp.com/matrix/imt.jsp?components=65623%3B64703%3B&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^] 以验证您的配置。

* 必须为所有FC和FCoE启动程序启用动态跟踪。



NOTE: NetApp AIX Host Utilities软件包位于上的link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp 支持站点"^]压缩tar.gz文件中。在将AIX MPIO与NetApp ONTAP存储结合使用时、必须安装AIX Host Utilities套件。

.步骤
. 登录到主机。
+
** 在 AIX 主机上，以 * 根 * 身份登录。
** 在PowerVM主机上，以*padmin*身份登录，然后输入 `oem_setup_env`命令以成为root用户。


. 转到 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["NetApp 支持站点"^]、并将包含Host Utilities的压缩文件下载到主机上的目录中。
. 转到包含下载内容的目录。
. 解压缩文件并提取SAN工具包软件包：
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
解压缩文件时将创建以下目录： `ntap_aix_host_utilities_7.0`。此目录包含以下子目录之一：MPIO、NNO_MPIO或SAN_Tool_Kit。

. 安装 AIX MPIO ：
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. 安装SAN工具包：
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. 重新启动主机。
. 验证安装。
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. 确认软件版本：
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
.  `lbp_enabled`运行以下命令、验证是否已将SCSI UNMAP参数添加到ODM：
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== SAN 工具包

AIX Host Utilities是一个NetApp主机软件、可在IBM AIX主机上提供命令行工具包。此工具包会在您安装 NetApp Host Utilities 软件包时安装。此套件提供 `sanlun` 实用程序、可帮助您管理LUN和主机总线适配器(HBA)。。 `sanlun` 命令将返回有关映射到主机的LUN的信息、多路径以及创建启动程序组所需的信息。

* 示例 *

在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[listing]
----
# sanlun lun show all
----
*示例输出*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: 此工具包适用于所有Host Utilities配置和协议。因此，其中某些内容适用于一种配置，而不适用于另一种配置。未使用的组件不会影响系统性能。AIX 和 PowerVM/VIOS 操作系统版本支持 SAN 工具包。
