---
sidebar: sidebar 
permalink: hu-luhu-release-notes.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Linux 主机实用程序发行说明 
---
= Linux 主机实用程序发行说明
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
发行说明介绍了使用ONTAP存储系统配置和管理特定主机的新功能、增强功能、已修复的问题、已知问题、限制和重要注意事项。

有关Host Utilities支持的操作系统版本和更新的特定信息，请参阅link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]。



== Linux Host Utilities 8.0 中的新功能

Linux Host Utilities 8.0 版本包含以下新功能和增强功能

Linux Host Utilities 8.0 包括对 64 位速度 QLogic 和 Emulex FC 主机总线适配器 (HBA) 的支持。

支持以下操作系统：

* Red Hat Enterprise Linux (RHEL) 9 和 8 系列
* SUSE Linux Enterprise Server
* Oracle Linux 9 和 8 系列
* Ubuntu




== Linux Host Utilities 7.1 中的新功能

Linux Host Utilities 7.1版包含以下新增功能和增强功能：

* Linux Host Utilities现在称为_Linux Unified Host Utilities _、因为它支持运行SANtricity的NetApp E系列存储系统以及运行ONTAP的AFF、FAS和ASA系统。
* 支持以下操作系统：
+
** Citrix XenServer
** KVM 和 XEN、RHEV 6.5 和 6.4
** Oracle VM 3.2系列
** Oracle Linux 7 和 6 系列
** RHEL 7 和 6 系列
** SUSE Linux Enterprise Server 15系列
** SUSE Linux Enterprise Server 11 SP4


* 在 RHEL 6 和 7 主机上，现在支持用于设置服务器配置文件的调整包。您可以使用 `tuned-adm`命令根据环境设置不同的配置文件。例如，当使用企业存储阵列的 LUN 时，您可以使用虚拟来宾配置文件作为来宾虚拟机，并使用企业存储配置文件进行配置。使用这些经过调整的软件包可以提高ONTAP的吞吐量和延迟。
* Linux Host Utilities 7.1 增加了对 Broadcom Emulex 和 Marvell Qlogic 的 32GB FC 适配器的支持。



NOTE: NetApp继续与 Linux Host Utilities 合作，以增加对初始版本之后的功能的支持。有关支持的功能和新增功能的最新信息，请参阅link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]。



== 已修复的问题

Linux Host Utilities 中已修复以下问题。

[cols="20, 80"]
|===
| 已修复版本 | Description 


| 7.1 | 运行时发生的间歇性主机操作系统故障问题 `sanlun lun show -p`SUSE Linux Enterprise Server 12 SP1、Oracle Linux 7.2、RHEL 7.2 和 RHEL 6.8 中的命令。 
|===


== 已知问题和限制

您应该注意以下可能影响特定主机性能的已知问题和限制：

[cols="15, 15, 30, 40"]
|===
| NetApp 错误 ID | 影响版本 | 标题 | Description 


| 1457017 | 7.1 | `sanlun`安装问题与`libdevmapper.so`和`libnl.so`库相关的警告消息。这些警告不会影响`sanlun` kit的功能。 | 在 SAN 主机上执行 Linux Host Utilities CLI 命令“sanlun fcp show adapter -v”时，该命令失败并显示一条错误消息，显示无法找到主机总线适配器 HBA 发现所需的库依赖项：
`[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded`请参阅NetApp在线错误 -link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^] 。 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bug Online"^] 提供有关大多数已知问题的完整信息、包括可能的建议解决方法。



== 下一步

link:hu-luhu-80.html["了解如何安装 Linux 主机实用程序"]
