---
sidebar: sidebar 
permalink: hu-luhu-sanlun-utility.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 介绍如何在ONTAP中使用Linux主机实用程序7.1 
---
= 了解ONTAP存储的“sanlun”实用程序
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilities 是一款NetApp主机软件，提供 `sanlun`Linux 主机上的命令。这 `sanlun`当您安装NetApp Host Utilities 包时，该实用程序会自动安装。此实用程序提供 `sanlun`可用于管理ONTAP LUN 和主机总线适配器 (HBA) 的命令。这 `sanlun`命令返回有关映射到主机的ONTAP LUN、多路径以及创建启动器组所需信息的信息。

在以下示例中， `sanlun lun show all`命令返回ONTAP LUN 信息：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* 对于 Linux Host Utilities 7.1，“sanlun”实用程序在 Host Utilities 的所有配置和协议中都是通用的。因此，它的某些内容适用于一种配置，但不适用于另一种配置。未使用的组件不会影响系统性能。
* 以下虚拟机管理程序类型不支持“sanlun”实用程序：
+
[role="tabbed-block"]
====
.8.0
--
对于 Linux Host Utilities 8.0，“sanlun”实用程序不支持 Citrix XenServer、Oracle VM 和 Red Hat Enterprise Virtualization。

--
.7.1
--
对于 Linux Host Utilities 7.1，“sanlun”实用程序不支持 Citrix Xenserver、Red hat Enterprise Virtualization 和 Proxmox。

--
====


====


== 下一步是什么？

link:hu-luhu-command-reference.html["了解如何使用Linux Host Utilities工具"] 。
