---
sidebar: sidebar 
permalink: hu-luhu-80.html 
keywords: host utilities, unified, oracle, linux, 8.0, netapp, ontap 
summary: 介绍如何将 Linux Host Utilities 8.0 与ONTAP结合使用 
---
= 为ONTAP存储安装 Linux Host Utilities 8.0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilities 可帮助您管理连接到 Linux 主机的ONTAP存储。 NetApp强烈建议安装 Linux Host Utilities，但这不是强制性的。这些实用程序可改善管理并帮助NetApp客户支持收集有关您的配置的信息。

Linux Host Utilities 8.0 支持以下分发类型：

* Red Hat Enterprise Linux (RHEL)
* SUSE Linux Enterprise Server
* Oracle Linux
* Ubuntu



NOTE: Linux Host Utilities软件不支持基于光纤通道的NVMe (NVMe/FC)和基于TCP的NVMe (NVMe/TCP)主机协议。

.关于此任务
当您安装 Linux 主机实用程序时，它不会更改 Linux 主机上的任何设置。

.开始之前
* 为了可靠运行，使用link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的 iSCSI、FC 或 FCoE 配置是否受支持。
* 安装供应商支持站点上提供的主机总线适配器 (HBA) 管理包。管理软件可实现 `sanlun`命令来收集有关 FC HBA 的信息，例如其 WWPN。
+
请参阅供应商文档来验证以下软件包是否正确安装。这些软件包需要支持 `sanlun fcp show adapter`命令：

+
** Marvell QLogic HBA—QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand Manager核心应用程序CLI




.步骤
. 如果您当前安装了某个版本的 Linux Host Utilities，请将其删除：
+
[role="tabbed-block"]
====
.Linux 主机
--
从 RHEL、SUSE Linux Enterprise Server 或 Oracle Linux 主机中删除 Linux Host Utilities：

[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-x-x
----
--
.Ubuntu
--
从 Ubuntu 主机中删除 Linux 主机实用程序：

[source, cli]
----
sudo apt remove netapp_linux_unified_host_utilities-x-x
----
--
====
+
对于早期版本的Linux Host Utilities、请转到安装主机实用程序软件的目录、然后输入uninstall命令以删除已安装的软件包。

. NetApp Linux Host Utilities 软件包可在NetApp支持站点上以 64 位 .rpm 文件的形式获取。从link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/8.0/downloads["NetApp 支持站点"^]给你的主人。
. 进入下载软件包的目录并安装：
+
[role="tabbed-block"]
====
.Linux 主机
--
在 RHEL、SUSE Linux Enterprise Server 或 Oracle Linux 主机上安装 Linux Host Utilities 8.0：

[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-8-0.x86_xx.rpm
----
您应该会看到类似于以下示例的输出：

[listing]
----
rpm -ivh netapp_linux_unified_host_utilities-8-0.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]

----
--
.Ubuntu
--
.. 在 Ubuntu 主机上安装 Linux Host Utilities 8.0：
+
[source, cli]
----
sudo apt install /<path_to_file>/netapp_linux_unified_host_utilities-8-0.x86_xx.deb
----
.. 手动将 Ubuntu 操作系统链接到 HBA 库：
+
[source, cli]
----
cp /opt/QLogic_Corporation/QConvergeConsoleCLI/lib64/libHBAAPI.so.2.0.2 /usr/lib64/libHBAAPI.so
----


--
====
. 验证安装。
+
[source, cli]
----
sanlun version
----
+
您应该会看到类似于以下示例的输出：

+
[listing]
----
sanlun version 8.0.386.1644
----




== 下一步是什么？

* Linux内核的建议驱动程序设置
+
如果您配置的FC环境使用Linux内核捆绑的本机收件箱驱动程序、则可以使用这些驱动程序的默认值。

* link:hu-luhu-sanlun-utility.html["了解“三仑”实用程序"] 。

