---
sidebar: sidebar 
permalink: hu-solaris-114.html 
keywords: host utilities, solaris, 114, netapp, ontap 
summary: 介绍如何将 IBM AIX 7.2 和 / 或 PowerVM VIOS 3.1 与 ONTAP 结合使用 
---
= 使用ONTAP存储为 FCP 和 iSCSI 配置 Solaris 11.4
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris Host Utilities 软件为连接到ONTAP存储的 Solaris 主机提供管理和诊断工具。在 Solaris 11.4 主机上安装 Solaris Host Utilities 时，您可以使用 Host Utilities 帮助您管理ONTAP LUN 的 FCP 和 iSCSI 协议操作。



== 第1步：(可选)启用SAN启动

您可以配置主机以使用 SAN 启动来简化部署并提高可扩展性。如果您的配置不支持 SAN 启动，您可以使用本地启动。

[role="tabbed-block"]
====
.SAN 启动
--
SAN 启动是将 SAN 连接磁盘 (LUN) 设置为 Solaris 主机的启动设备的过程。您可以设置 SAN 启动 LUN，以在使用 FC 协议并运行 Solaris Host Utilities 的 Solaris MPxIO 环境中工作。设置 SAN 启动 LUN 的方法取决于您的卷管理器和文件系统。

.步骤
. 使用link:https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的 Solaris 操作系统、协议和ONTAP版本是否支持 SAN 启动。
. 按照 Solaris 供应商文档中有关设置 SAN 启动的最佳实践进行操作。


--
.本地启动
--
通过在本地硬盘上安装 Solaris OS 执行本地引导，例如，安装在 SSD、SATA 或 RAID 上。

--
====


== 步骤 2：安装 Solaris 主机实用程序

NetApp强烈建议安装 Solaris Host Utilities 来支持ONTAP LUN 管理并协助技术支持收集配置数据。


NOTE: 安装 Solaris Host Utilities 会更改 Solaris 主机上的某些超时设置。

link:hu-solaris-80.html["安装 Solaris Host Utilities 8.0"] 。



== 第3步：确认主机的多路径配置

您可以使用 Solaris 11.4 的多路径来管理ONTAP LUN。

多路径使您能够在主机和存储系统之间配置多条网络路径。如果一条路径发生故障，流量仍可通过其余路径继续传输。对于 Solaris 11.4 和 SPARC 系统，Oracle Solaris I/O 多路径 (MPxIO) 默认启用。

为确保为您的主机正确配置多路径和建议的超时参数，请验证您是否使用了NetApp为ONTAP LUN 推荐的设置。

.步骤
. 如果您的主机配置了 FC，请验证 `/kernel/drv/fp.conf`设置为 `mpxio-disable="no"`。
. Solaris Host Utilities 加载NetApp针对 SPARC 和 x86_64 处理器推荐的参数设置。
+
.显示参数设置
[%collapsible]
====
[cols="2*"]
|===
| 参数 | 价值 


| throttle_max | 8. 


| not_ready_retries | 300 


| busy_retries | 30 个 


| reset_retries | 30 个 


| throttle_min | 2. 


| timeout_retries | 10 


| 物理块大小 | 4096 


| 磁盘排序 | false 


| 缓存非易失性 | true 
|===
====
+
有关 Solaris 11.4 系统设置的其他信息，请参阅 Oracle 支持 DOC ID：2595926.1。

. 如果您的存储配置包括MetroCluster、Oracle Solaris 虚拟化或SnapMirror活动同步，请更改默认设置：
+
[role="tabbed-block"]
====
.MetroCluster
--
默认情况下，如果到 LUN 的所有路径都丢失，Solaris OS 将在 *20 秒* 后无法执行 I/O 操作。这是由 `fcp_offline_delay`范围。默认值为 `fcp_offline_delay`适用于标准ONTAP集群。但是，在MetroCluster配置中，您必须增加 `fcp_offline_delay`至 *120 秒*，以确保 I/O 在操作期间不会过早超时，包括计划外的故障转移。

有关MetroCluster默认设置的其他信息和建议更改，请参阅知识库文章 https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["MetroCluster 配置中的 Solaris 主机支持注意事项"^]。

--
.Oracle Solaris虚拟化
--
** Solaris 虚拟化选项包括 Solaris 逻辑域（也称为 LDOM 或 Oracle VM Server for SPARC）、Solaris 动态域、Solaris 区域和 Solaris 容器。这些技术也被称为“Oracle虚拟机”。
** 您可以一起使用多个选项，例如，特定 Solaris 逻辑域内的 Solaris 容器。
** NetApp支持使用 Solaris 虚拟化技术，其中整体配置由 Oracle 支持，并且任何可直接访问 LUN 的分区都列在link:https://imt.netapp.com/matrix/#welcome["IMT"]在受支持的配置中。这包括根容器、LDOM I/O 域和使用 NPIV 访问 LUN 的 LDOM。
** 仅使用虚拟化存储资源的分区或虚拟机，例如 `vdsk`，不需要特定资格，因为他们无法直接访问ONTAP LUN。您只需验证对底层 LUN 具有直接访问权限的分区或虚拟机（例如 LDOM I/O 域）是否列在link:https://imt.netapp.com/matrix/#welcome["IMT"^]。


.步骤
当 LUN 用作 LDOM 内的虚拟磁盘设备时，LUN 的源会被虚拟化屏蔽，并且 LDOM 无法正确检测块大小。为了防止出现此问题：

.. 为 LDOM OS 修补_Oracle Bug 15824910_
.. 创建一个 `vdc.conf`将虚拟磁盘的块大小设置为 `4096`。有关详细信息，请参阅 Oracle DOC：2157669.1。
.. 验证补丁安装以确保已正确配置推荐的设置：
+
... 创建 zpool：
+
[source, cli]
----
zpool create zpool_name disk_list
----
... 运行 `zdb -C` 并验证*ashift,的值是否为 `12`。
+
如果 *ashift* 的值不是 `12`，重新运行 `zdb -C11`，并验证是否安装了正确的补丁并重新检查 `vdc.conf`。

+
直到 *ashift* 显示值 `12`。






NOTE: 针对多个 Solaris 版本上的 Oracle 错误 15824910 提供了补丁。如果您需要帮助确定最佳内核补丁，请联系 Oracle。

--
.SnapMirror主动同步
--
从ONTAP 9.9.1 开始，Solaris 主机支持SnapMirror主动同步设置配置。要验证在SnapMirror主动同步环境中发生计划外站点故障转移切换时 Solaris 客户端应用程序是否不会中断，必须配置 `scsi-vhci-failover-override`Solaris 主机上的设置。此设置覆盖故障转移模块 `f_tpgs`阻止执行检测到矛盾的代码路径。

.步骤
.. 创建配置文件 `/etc/driver/drv/scsi_vhci.conf`对于连接到主机的NetApp存储类型，其条目类似于以下示例：
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
.. 验证覆盖参数是否已成功应用：
+
[source, cli]
----
devprop
----
+
[source, cli]
----
mdb
----
+
.显示示例
[%collapsible]
=====
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k
----
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----
=====



NOTE: 之后 `scsi-vhci-failover-override` 已应用、 `conf` 已添加到 `svl_fops_name`。有关追加信息和建议的默认设置更改、请参阅NetApp知识库文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris主机支持SnapMirror主动同步配置中的建议设置"^]。

--
====
. 验证使用ONTAP LUN 的 zpools 是否支持 4 KB 对齐的 I/O：
+
.. 验证您的 Solaris 主机是否安装了最新的支持存储库更新 (SRU)：
+
[source, cli]
----
pkg info entire`
----
.. 验证ONTAP LUN 是否具有 `ostype`作为“Solaris”，与 LUN 大小无关：
+
[source, cli]
----
lun show -vserver` <vsersver_name>
----
+
.显示示例
[%collapsible]
====
[listing]
----
chat-a800-31-33-35-37::*> lun show -vserver solaris_fcp -path /vol/sol_195_zpool_vol_9/lun -fields ostype
vserver     path                         ostype
----------- ---------------------------- -------
solaris_fcp /vol/sol_195_zpool_vol_9/lun solaris
----
====


. 验证ONTAP LUN 的输出：
+
[source, cli]
----
sanlun lun show
----
+
对于ASA、 AFF或FAS配置，您应该会看到与以下示例类似的输出：

+
.显示示例
[%collapsible]
====
[listing]
----
root@sparc-s7-55-148:~# sanlun lun show -pv

                    ONTAP Path: Solaris_148_siteA:/vol/Triage/lun
                           LUN: 0
                      LUN Size: 20g
                   Host Device: /dev/rdsk/c0t600A098038314B32685D573064776172d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----
====
. 验证ONTAP LUN 的路径状态：
+
[source, cli]
----
mpathadm show lu <LUN>`
----
+
以下示例输出显示ASA、 AFF或FAS配置中ONTAP LUN 的正确路径状态。输出中每个 LUN 的“访问状态”都会显示路径优先级。

+
[role="tabbed-block"]
====
.ASA配置
--
ASA配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
root@sparc-s7-55-82:~# mpathadm show lu /dev/rdsk/c0t600A098038313953495D58674777794Bd0s2
Logical Unit:  /dev/rdsk/c0t600A098038313953495D58674777794Bd0s2
        mpath-support:  libmpscsi_vhci.so
        Vendor:  NETAPP
        Product:  LUN C-Mode
        Revision:  9171
        Name Type:  unknown type
        Name:  600a098038313953495d58674777794b
        Asymmetric:  yes
        Current Load Balance:  round-robin
        Logical Unit Group ID:  NA
        Auto Failback:  on
        Auto Probing:  NA

        Paths:
                Initiator Port Name:  100000109bd30070
                Target Port Name:  20b9d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109bd30070
                Target Port Name:  20b8d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109bd3006f
                Target Port Name:  20b3d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109bd3006f
                Target Port Name:  20b4d039ea593393
                Logical Unit Number:  0
                Override Path:  NA
                Path State:  OK
                Disabled:  no

        Target Port Groups:
                ID:  1003
                Explicit Failover:  no
                Access State:  *active optimized*
                Target Ports:
                        Name:  20b9d039ea593393
                        Relative ID:  8

                        Name:  20b4d039ea593393
                        Relative ID:  3

                ID:  1002
                Explicit Failover:  no
                Access State:  *active optimized*
                Target Ports:
                        Name:  20b8d039ea593393
                        Relative ID:  7

                        Name:  20b3d039ea593393
                        Relative ID:  2
----
=====
--
.AFF或FAS配置
--
AFF或FAS配置应具有两组优先级较高和较低的路径。优先级较高的主动/优化路径由聚合所在的控制器提供。优先级较低的路径处于活动状态、但未进行优化、因为它们由其他控制器提供服务。只有在优化路径不可用时、才会使用非优化路径。

以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出：

.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
root@chatsol-54-195:~# mpathadm show lu /dev/rdsk/c0t600A0980383044376C3F4E694E506E44d0s2
Logical Unit:  /dev/rdsk/c0t600A0980383044376C3F4E694E506E44d0s2
        mpath-support:  libmpscsi_vhci.so
        Vendor:  NETAPP
        Product:  LUN C-Mode
        Revision:  9171
        Name Type:  unknown type
        Name:  600a0980383044376c3f4e694e506e44
        Asymmetric:  yes
        Current Load Balance:  round-robin
        Logical Unit Group ID:  NA
        Auto Failback:  on
        Auto Probing:  NA

        Paths:

                Initiator Port Name:  100000109b56c5fb
                Target Port Name:  205200a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Disabled:  no

                Initiator Port Name:  100000109b56c5fb
                Target Port Name:  205000a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Demoted:  yes
                Disabled:  no

                Initiator Port Name:  100000109b56c5fa
                Target Port Name:  204f00a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Demoted:  yes
                Disabled:  no

                Initiator Port Name:  100000109b56c5fa
                Target Port Name:  205100a098ba7afe
                Logical Unit Number:  1
                Override Path:  NA
                Path State:  OK
                Disabled:  no

        Target Port Groups:
                ID:  1001
                Explicit Failover:  no
                Access State:  *active not optimized*
                Target Ports:
                        Name:  205200a098ba7afe
                        Relative ID:  8

                        Name:  205100a098ba7afe
                        Relative ID:  7

                ID:  1000
                Explicit Failover:  no
                Access State:  *active optimized*
                Target Ports:
                        Name:  205000a098ba7afe
                        Relative ID:  6

                        Name:  204f00a098ba7afe
                        Relative ID:  5
----
=====
--
====




== 步骤 4：查看已知问题

适用于带有ONTAP存储的 FCP 和 iSCSI 的 Solaris 11.4 版本存在以下已知问题：

[cols="4*"]
|===
| NetApp 错误 ID | 标题 | Description | Oracle ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1362435["1362435"^] | Huk 6.2 和 Solaris_11.4 FC 驱动程序绑定更改 | 请参见Solaris 11.4和HUK建议。FC驱动程序绑定已从更改为 `ssd (4D)` to `sd (4D)`。从移动现有配置 `ssd.conf` to `sd.conf` 如Oracle文档2595926.1中所述)。在新安装的Solaris 11.4系统和从Solaris 11.3或更早版本升级的系统中，此行为会有所不同。 | （文档 ID 2595926.1 ） 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1366780["1366780"^] | 在x86 Arch上使用Emulex 32G主机总线适配器(HBA)执行存储故障转移(Storage Failover、SFo)恢复操作期间、系统会注意到Solaris LIF问题描述 | 在x86_64平台上、Emulex固件版本12.6.x及更高版本会注意到Solaris LIF问题描述。 | SR 3-24746803021 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1368957["1368957"^] | Solaris 11.x `cfgadm -c configure` 导致端到端Emulex配置出现I/O错误 | 正在运行 `cfgadm -c configure` 在Emulex上、端到端配置会导致I/O错误。此问题已在ONTAP 9.5P17、9.6P14、9.7P13和9.8P2中得到修复 | 不适用 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1345622["1345622"^] | 使用操作系统本机命令在具有ASA/pport的Solaris主机上报告异常路径 | 在使用全SAN阵列(ASA)的Solaris 11.4上发现间歇性路径报告问题。 | 不适用 
|===


== 下一步是什么？

link:hu-solaris-command-reference.html["了解如何使用 Solaris Host Utilities 工具"] 。
