---
sidebar: sidebar 
permalink: hu-veritas-7x.html 
keywords: host utilities, veritas, infoscale, 7, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: 提供有关 Veritas Infoscale 7 系列版本的 ONTAP SAN 主机配置设置的指导 
---
= 配置 Veritas Infoscale 7 以支持 FC、FCoE 和 iSCSI 以及ONTAP存储
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilities 软件为连接到ONTAP存储的 Linux 主机提供管理和诊断工具。使用 Veritas Infoscale 7 的 Linux 主机实用程序，支持 Oracle Linux（基于 Red Hat 兼容内核）、Red Hat Enterprise Linux (RHEL) 和 SUSE Linux Enterprise Server 主机，以支持使用ONTAP LUN 管理 FC、FCoE 和 iSCSI 协议操作。



== 第1步：(可选)启用SAN启动

您可以将主机配置为使用SAN启动来简化部署并提高可扩展性。

.开始之前
* 使用link:https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的Linux操作系统、主机总线适配器(HBA)、HBA固件、HBA启动BIOS和ONTAP版本是否支持SAN启动。
* 请参阅 Veritas 支持门户（产品矩阵、平台查找和 HCL 矩阵）以验证 SAN 启动配置支持和已知问题。


.步骤
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["创建 SAN 启动 LUN 并将其映射到主机"^](英文)
. 在服务器 BIOS 中为 SAN 启动 LUN 映射到的端口启用 SAN 启动。
+
有关如何启用 HBA BIOS 的信息，请参见供应商专用文档。

. 重新启动主机并验证操作系统是否已启动且正在运行、以验证配置是否成功。




== 第2步：安装Linux Host Utilities

NetApp强烈推荐 link:hu-luhu-release-notes.html["安装 Linux 主机实用程序"] 支持ONTAP LUN 管理，并协助技术支持收集配置数据。


NOTE: 安装Linux Host Utilities不会更改Linux主机上的任何主机超时设置。



== 步骤 3：确认主机上的 Veritas 动态多路径配置

使用 Veritas 动态多路径 (VxDMP) 和 Veritas Infoscale 7 来管理ONTAP LUN。

为确保 VxDMP 已正确配置到您的主机上，您需要验证 VxDMP 配置，并检查阵列支持库 (ASL) 和阵列策略模块 (APM) 配置。NetApp存储系统的 ASL 和 APM 软件包是在 Veritas 软件安装过程中安装的。


NOTE: 对于异构多路径环境，包括 Veritas Infoscale、Linux Native Device Mapper 和 LVM 卷管理器，请参阅 Veritas 产品管理文档以了解配置设置。

.开始之前
请确保您的配置满足系统要求。参见 link:https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"^] 以及 Veritas HCL 矩阵。

.步骤
. 确认ONTAP目标阵列已连接到 VxDMP 多路径：
+
[source, cli]
----
vxdmpadm
----
+
.显示示例
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. 检查 ASL 和 APM 软件包的配置。NetApp建议您使用 Veritas 支持门户网站上列出的最新受支持软件包。
+
.展示 ASL 和 APM 配置示例
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. 为了在存储故障转移操作中获得最佳系统配置，请确认您已设置以下 Veritas VxDMP 可调参数：
+
[cols="2*"]
|===
| 参数 | 正在设置 ... 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval | 60 
|===
. 将DMP可调参数设置为在线：
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. 请确认可调参数设置正确：
+
[source, cli]
----
# vxdmpadm gettune
----
+
以下示例显示了 SAN 主机上有效的 VxDMP 可调参数。

+
.显示示例
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. 配置协议超时值：
+
[role="tabbed-block"]
====
.FC/FCoE
--
使用 FC 和 FCoE 的默认超时值。

--
.iSCSI
--
设置 `replacement_timeout` 参数值设为 120。

iSCSI `replacement_timeout` 该参数控制 iSCSI 层在超时路径或会话重新建立之前应等待多长时间，然后再拒绝对其执行任何命令。NetApp建议设置以下值： `replacement_timeout` 在 iSCSI 配置文件中设置为 120。

.示例
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. 设置 RHEL 8 和 9 系列主机的主机“udev rport”值，以支持 Veritas Infoscale 环境在存储故障转移场景中的运行。
+
通过创建文件来配置“udev rport”值 `/etc/udev/rules.d/40-rport.rules` 文件内容如下：

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: 有关 Veritas 的所有其他特定设置，请参阅 Veritas Infoscale 标准产品文档。

. 验证ONTAP LUN的参数设置和路径状态：
+
在AFF、 FAS或ASA配置中，单个ONTAP LUN 不应需要超过四条路径。存储故障时，超过四条路径都可能导致问题。

+
以下示例显示了ASA、 AFF或FAS配置中ONTAP LUN 的正确参数设置和路径状态。

+
[role="tabbed-block"]
====
.ASA配置
--
ASA配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

.显示示例
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.AFF或FAS配置
--
AFF或FAS配置应具有两组优先级较高和较低的路径。优先级较高的主动/优化路径由聚合所在的控制器提供。优先级较低的路径处于活动状态、但未进行优化、因为它们由其他控制器提供服务。只有在优化路径不可用时、才会使用非优化路径。

以下示例显示了具有两个主动/优化路径和两个主动/非优化路径的ONTAP LUN的输出：

.显示示例
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== 第四步：已知问题

没有已知问题。



== 下一步是什么？

* link:hu-luhu-command-reference.html["了解如何使用Linux Host Utilities工具"] 。

