---
sidebar: sidebar 
permalink: hu-wuhu-80.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows Host Utilities 包含一个安装程序，该程序设置所需的 Windows 注册表和 HBA 参数，以便 Windows 主机正确处理ONTAP平台的存储系统行为。 
---
= 为ONTAP存储安装 Windows Host Utilities 8.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用Windows主机实用程序可以将Windows主机计算机连接到NetApp存储系统。

Windows Host Utilities支持以下Windows版本：

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016


Windows Host Utilities 包含一个安装程序，该程序设置所需的 Windows 注册表和主机总线适配器 (HBA) 参数，以便 Windows 主机可以正确处理ONTAP平台的存储系统行为。

安装Host Utilities软件时、安装程序会设置所需的Windows注册表和HBA参数。

Windows 主机计算机上安装了以下程序和文件。默认目录为 `C ： \Program Files\NetApp\Windows Host Utilities` 。

|===
| 计划 | 目的 


| ` \NetAppQCL1\fcconfig.exe` | 由安装程序用于设置HBA参数。 


| ` \NetAppQCL1\fcconfig.ini` | 由安装程序用于设置HBA参数。 


| `sA_version.exe` | 显示Host Utilities和FC HBA的版本。 
|===
Host Utilities支持不同的Windows主机配置、协议和多路径选项。有关详细信息，请参见 https://mysupport.netapp.com/matrix/["互操作性表工具"^]。



== 步骤 1：验证主机和存储系统配置

在安装 Windows Host Utilities 之前，请验证您的主机和存储系统配置是否受支持<<supported-windows-versions-80,支持的Windows版本>>。

.步骤
. 在中检查支持的配置 http://mysupport.netapp.com/matrix["互操作性表工具"^]。
. 检查 Windows Server 主机版本所需的修补程序link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主机Windows文档"]。
+
例如，link:https://docs.netapp.com/us-en/ontap-sanhost/hu-windows-2025.html["为Windows Server 2025配置ONTAP存储"]文档提供了为 Windows Server 2025 安装 Windows 修补程序的说明。

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["添加 iSCSI 或 FCP 许可证"^] 。
. 启动目标服务。
. 验证布线。
+
请参阅 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 配置参考"^]了解详细的布线和配置信息。





== 步骤 2：配置 FC HBA 和交换机

安装并配置一个或多个受支持的FC主机总线适配器(HBA)、以便与存储系统建立FC连接。

Windows Host Utilities安装程序可设置所需的FC HBA设置。


CAUTION: 您应该只允许 Windows Host Utilities 安装程序设置 HBA 参数。这可确保 Windows 主机能够正确处理ONTAP平台的存储系统行为。

.步骤
. 按照HBA供应商提供的说明安装一个或多个受支持的FC HBA。
. 获取受支持的 HBA 驱动程序和管理实用程序，并按照 HBA 供应商提供的说明进行安装。
. https://docs.netapp.com/us-en/ontap/san-management/index.html["将 HBA 连接到 FC 交换机或直接连接到存储系统"^] 。
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["根据 FC 交换机文档在 FC 交换机上创建区域"^] 。
. 对于ONTAP，按 WWPN 对交换机进行区域划分。请务必使用逻辑接口 (LIF) 的 WWPN，而不是存储控制器上的物理端口的 WWPN。请参阅 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 配置参考"^]了解更多信息。




== 步骤 3：安装 Windows 主机实用程序

安装程序安装 Windows Host Utilities 包并设置 Windows 注册表和 HBA 设置。

.关于此任务
您可以选择在安装 Windows Host Utilities 软件包时包含多路径支持。安装程序会提示您选择以下选项：

* 选择 `MPIO` 从Windows主机或虚拟机到存储系统的路径不止一个。
* 选择 `no MPIO`仅当您使用存储系统的单一路径时。


您还可以使用 Windows 命令行提示符选择多路径支持。

对于 Hyper-V 客户机，如果您选择多路径支持，则原始（直通）磁盘不会出现在客户机操作系统中。您可以使用原始磁盘或 MPIO，但不能在来宾操作系统中同时使用它们。


CAUTION: 如果不安装MPIO软件、则Windows操作系统可能会将每个路径视为一个单独的磁盘。这可能会导致数据损坏。


NOTE: 在Hyper-V虚拟机中运行的Windows XP或Windows Vista不支持MPIO。

.步骤
您可以交互方式或使用 Windows 命令行安装主机实用程序。新的 Host Utilities 安装包必须位于 Windows 主机可访问的路径中。

[role="tabbed-block"]
====
.以交互方式安装
--
通过运行安装程序并按照提示以交互方式安装 Windows Host Utilities 软件包。

. 从下载可执行文件 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["NetApp 支持站点"^]。
. 更改为下载可执行文件的目录。
. 运行 `netapp_windows_host_utilities_7.2_x64` 归档并按照屏幕上的说明进行操作。
. 出现提示时重新启动 Windows 主机。


--
.非交互安装
--
使用 Windows 命令行执行 Host Utilities 的非交互式安装。安装完成后系统自动重启。

. 在Windows命令提示符处输入以下命令：
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` 是的名称 `.msi` 适用于CPU架构的文件。
** 多路径用于指定是否安装 MPIO 支持。允许的值为"0"表示否、"1"表示是。
** `inst_path` 是安装 Host Utilities 文件的路径。默认路径为 `C ： \Program Files\NetApp\Windows Host Utilities\` 。





NOTE: 要查看用于日志记录和其他功能的标准Microsoft安装程序(MSI)选项、请输入 `msiexec /help` 在Windows命令提示符处。例如、 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 命令可显示日志记录信息。

--
====


== 下一步是什么？

link:hu_wuhu_hba_settings.html["配置 Windows Host Utilities 的注册表设置"] 。
