---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 介绍如何将 IBM AIX 7.2 和 / 或 PowerVM VIOS 3.1 与 ONTAP 结合使用 
---
= AIX Host Utilities 6.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
AIX统一主机实用程序可帮助您管理连接到AIX主机的NetApp ONTAP存储。



== SAN 工具包

AIX Host Utilities 是一种 NetApp 主机软件，可在 IBM AIX 主机上提供命令行工具包。此工具包会在您安装 NetApp Host Utilities 软件包时安装。此套件提供 `sanlun` 实用程序，可帮助您管理 LUN 和 HBA 。`sanlun` 命令可返回有关映射到主机的 LUN 的信息，多路径以及创建启动程序组所需的信息。

* 示例 *

在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[listing]
----
#sanlun lun show all

controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: 此工具包在 Host Utilities 的所有配置和协议中通用。因此，其中某些内容适用于一种配置，而不适用于另一种配置。未使用的组件不会影响系统性能。


NOTE: AIX 和 PowerVM/VIOS 操作系统版本支持 SAN 工具包。



== 安装 AIX Host Utilities

上提供了 NetApp AIX Host Utilities 软件包 https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host%2BUtilities%2B-%2BSAN&platform=Linux["NetApp 支持站点"^] 在经过压缩的 tar.gz 文件中。

在将 AIX MPIO 与 NetApp ONTAP 存储结合使用时，必须安装 AIX 主机实用程序套件。

您可以从 NetApp 支持站点下载包含 Host Utilities 软件包的压缩文件。下载此文件后，您必须对其进行解压缩，以获取安装 Host Utilities 所需的两个软件包。

* 步骤 *

. 登录到主机。
+
** 在 AIX 主机上，以 * 根 * 身份登录。
** 在 PowerVM 主机上，以 * padmin* 身份登录，然后输入 oem_setup_env 命令以成为 root 。


. 从 NetApp 支持站点将包含 Host Utilities 的压缩文件副本下载到主机上的目录中。
. 转到包含下载内容的目录。
. 解压缩文件并提取 SAN 工具包软件包。
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
解压缩文件时会创建以下目录： `ntap_aix_host_utilities_6.1` 。此目录将包含以下子目录之一： MPIO ， non_MPIO 或 SAN_Tool_Kit

. 安装 AIX MPIO ：
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. 安装 SAN 工具包：
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit netapp.SAN_toolkit`

. 重新启动主机。
. 验证安装。
+
`sanlun 版本`


