---
sidebar: sidebar 
permalink: hu_aix_72.html 
keywords: Host Utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 介绍如何将 IBM AIX 7.2 和 / 或 PowerVM VIOS 3.1 与 ONTAP 结合使用 
---
= 使用ONTAP存储为 FCP 和 iSCSI 配置 AIX 7.2/VIOS 3.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX Host Utilities 软件为连接到ONTAP存储的 AIX 主机提供管理和诊断工具。在 AIX 7.2 和/或 PowerVM（VIOS 3.1）主机上安装 AIX Host Utilities 时，您可以使用 Host Utilities 来帮助您管理ONTAP LUN 的 FCP 和 iSCSI 协议操作。



== 第1步：(可选)启用SAN启动

您可以配置主机以使用 SAN 启动来简化部署并提高可扩展性。如果您的配置不支持 SAN 启动，您可以使用本地启动。

[role="tabbed-block"]
====
.SAN 启动
--
SAN 启动是将 SAN 连接磁盘（LUN）设置为 AIX/PowerVM 主机的启动设备的过程。您可以设置 SAN 启动 LUN 以在使用 FC 协议并使用 FC 或 FCoE 协议运行 AIX Host Utilities 的 AIX 多路径 I/O (MPIO) 环境中工作。在 AIX MPIO 环境中创建 SAN 启动 LUN 和安装新 OS 映像的方法取决于您使用的协议。

.步骤
. 使用link:https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的 AIX OS、协议和ONTAP版本是否支持 SAN 启动。
. 按照供应商文档中有关设置 SAN 启动的最佳实践进行操作。


--
.本地启动
--
通过在本地硬盘（例如 SSD、SATA 或 RAID）上安装 AIX OS 来执行本地启动。

--
====


== 第 2 步：安装 AIX 主机实用程序

NetApp强烈建议安装 AIX Host Utilities 来支持ONTAP LUN 管理并协助技术支持收集配置数据。  Host Utilities 中的 MPIO 包为 AIX 和 VIOS 提供 MPIO 支持。


NOTE: 安装 AIX Host Utilities 可为您的 AIX 主机提供额外的超时设置。

link:hu_aix_61.html["安装 AIX Host Utilities 6.1"] 。



== 第3步：确认主机的多路径配置

您可以使用 AIX 7.2 和 PowerVM 的多路径来管理ONTAP LUN。

多路径允许您在主机和存储系统之间配置多条网络路径。如果一条路径发生故障，流量仍可通过剩余路径继续传输。  Host Utilities 的 AIX 和 PowerVM 环境使用 AIX 本机多路径解决方案 (MPIO)。

路径控制模块 (PCM) 负责控制 AIX 主机的多条路径。  PCM 是存储供应商提供的代码，用于处理路径管理，在 Host Utilities 安装期间安装并启用。

为确保为您的主机正确配置多路径，请验证您是否已为您的ONTAP LUN 配置NetApp推荐的设置。

. AIX Host Utilities 为ONTAP LUN 加载以下参数设置。
+
.显示参数设置
[%collapsible]
====
[cols="4*"]
|===
| 参数 | environment | AIX 的价值 | 注意 


| 算法 | MPIO | 循环 | 由 Host Utilities 设置 


| hcheck_cmd | MPIO | 查询 | 由 Host Utilities 设置 


| hcheck_interval | MPIO | 30 个 | 由 Host Utilities 设置 


| hcheck_mode | MPIO | 非活动 | 由 Host Utilities 设置 


| lun_reset_st | MPIO / 非 MPIO | 是的。 | 由 Host Utilities 设置 


| max_transfer | MPIO / 非 MPIO | FC LUN ： 0x100000 字节 | 由 Host Utilities 设置 


| QFull | MPIO / 非 MPIO | 2 秒延迟 | 由 Host Utilities 设置 


| queue_depth | MPIO / 非 MPIO | 64 | 由 Host Utilities 设置 


| reserve_policy | MPIO / 非 MPIO | no_reserve | 由 Host Utilities 设置 


| re_timeout （磁盘） | MPIO / 非 MPIO | 30 秒 | 使用操作系统默认值 


| dyntrk | MPIO / 非 MPIO | 是的。 | 使用操作系统默认值 


| FC_err_recov | MPIO / 非 MPIO | fast_fail | 使用操作系统默认值 


| q_type | MPIO / 非 MPIO | 简单 | 使用操作系统默认值 


| num_cmd_elems | MPIO / 非 MPIO | 对于 AIX 3072 ，对于 VIOS 为 1024 | FC EN1B ， FC EN1C 


| num_cmd_elems | MPIO / 非 MPIO | 1024 （用于 AIX ） | FC EN0G 
|===
====
. 如果您的存储配置包括MetroCluster或SnapMirror活动同步，请更改默认设置：
+
[role="tabbed-block"]
====
.MetroCluster
--
默认情况下，当没有可用的 LUN 路径时，AIX OS 会强制执行较短的 I/O 超时。这可能发生在包含单交换机 SAN 结构的配置中以及经历计划外故障转移的MetroCluster配置中。有关其他信息和建议对默认设置进行更改，请参阅知识库文章link:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["MetroCluster配置中的 AIX 主机支持注意事项有哪些？"^]。

--
.SnapMirror主动同步
--
从ONTAP 9.11.1 开始，AIX 主机支持SnapMirror主动同步。  AIX 配置中的主集群是“活动”集群。

在 AIX 配置中，故障转移会造成破坏。每次故障转移时，您都需要在主机上执行重新扫描以恢复 I/O 操作。

请参阅知识库文章link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["如何为SnapMirror活动同步配置AIX主机"^]。

--
====
. 验证ONTAP LUN 的路径状态：
+
[source, cli]
----
sanlun lun show
----
+
以下示例输出显示ASA、 AFF或FAS配置中ONTAP LUN 的正确路径状态。

+
[role="tabbed-block"]
====
.ASA配置
--
ASA配置优化了到给定 LUN 的所有路径，使其保持活动状态（“主要”）。通过同时通过所有路径提供 I/O 操作，可以提高性能。

.显示示例
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----
=====
--
.AFF或FAS配置
--
AFF或FAS配置应具有两组优先级较高和较低的路径。优先级较高的主动/优化路径由聚合所在的控制器提供。优先级较低的路径处于活动状态、但未进行优化、因为它们由其他控制器提供服务。只有在优化路径不可用时、才会使用非优化路径。

以下示例显示具有两个主动/优化（“主”）路径和两个主动/非优化（“次”）路径的ONTAP LUN 的正确输出：

.显示示例
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1
----
=====
--
====




== 步骤 4：查看已知问题



== 已知问题

带有ONTAP存储版本的 IBM AIX 7.2 和/或 PowerVM (VIOS 3.1) 存在以下已知问题：

[cols="4*"]
|===
| NetApp 错误 ID | 标题 | Description | 合作伙伴 ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1416221["1416221."^] | AIX 7200-05-01 在存储故障转移期间遇到虚拟 iSCSI 磁盘（ VIOS 3.1.1.x ）的 I/O 中断 | 在通过 VIOS 3.1.1.x 映射的虚拟 iSCSI 磁盘上的 AIX 7.2 TL5 主机上执行存储故障转移操作期间，可能会发生 I/O 中断默认情况下， VIOC 上虚拟 iSCSI 磁盘（ hdisk ）的 `rw_timeout` 值将为 45 秒。如果在存储故障转移期间发生超过 45 秒的 I/O 延迟，则可能会发生 I/O 故障。要避免这种情况，请参见 BURT 中所述的临时解决策。根据 IBM 的要求，在应用 APAR - IJ34739 （即将发布的版本）后，我们可以使用 `chdev` 命令动态更改 rw_timeout 值。 | 不适用 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1414700["1414700"^] | 在存储故障转移期间， AIX 7.2 TL04 的虚拟 iSCSI 磁盘（ VIOS 3.1.1.x ）发生 I/O 中断 | 在通过 VIOS 3.1.1.x 映射的虚拟 iSCSI 磁盘上的 AIX 7.2 TL4 主机上执行存储故障转移操作期间，可能会发生 I/O 中断默认情况下， VIOC 上 vSCSI 适配器的 `rw_timeout` 值为 45 秒。如果在存储故障转移期间发生超过 45 秒的 I/O 延迟，则可能会发生 I/O 故障。要避免这种情况，请参见 BURT 中所述的临时解决策。 | 不适用 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1307653["1307653"^] | 在SFO故障和直接I/O期间、VIOS 3.1.1.10会发生I/O问题 | 在VIOS 3.1.1上、由16 GB或32 GB FC适配器提供后备支持的NPIV客户端磁盘可能发生I/O故障。此外、 `vfchost`驱动程序可能会停止处理来自客户端的I/O请求。应用IBM APAR IJ22290 IBM APAR IJ23222可解决此问题。 | 不适用 
|===


== 下一步是什么？

link:hu-aix-command-reference.html["了解如何使用 AIX Host Utilities 工具"] 。
