---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 介绍如何将 IBM AIX 7.2 和 / 或 PowerVM VIOS 3.1 与 ONTAP 结合使用 
---
= 安装适用于ONTAP存储的AIX Host Utilities 6.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX Host Utilities 可帮助您管理连接到 AIX 主机的ONTAP存储。  NetApp强烈建议安装 AIX Host Utilities 来改进ONTAP存储管理并协助NetApp支持收集有关您的配置的信息。

AIX Host Utilities 6.1 支持以下传输协议和 AIX 环境：

* FC、FCoE 和 iSCSI
* AIX Microsoft 多路径 I/O (MPIO)
* PowerVM
+
有关PowerVM的详细信息、请参见IBM PowerVM Live Partition Mobility红皮书。



.关于此任务
* 您需要安装带有 AIX MPIO 的 AIX Host Utilities SAN Toolkit 来管理连接到 AIX 主机的ONTAP存储。
* 当您安装 AIX Host Utilities 时，它们不会更改 AIX 主机上的任何设置。


.开始之前
* 使用link:https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的 AIX OS、协议和ONTAP版本是否支持 SAN 启动。
* 通过运行 `chdev -l <fscsi_device> -a dyntrk=ye`AIX 主机上的命令。


.步骤
. 登录到主机。
+
[role="tabbed-block"]
====
.AIX
--
在 AIX 主机上，以 * 根 * 身份登录。

--
.PowerVM
--
在 PowerVM 主机上：

.. 以 *padmin* 身份登录。
.. 成为 root 用户：
+
[source, cli]
----
oem_setup_env
----


--
====
. 转至 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["NetApp 支持站点"^] 并将包含Host Utilities的压缩文件下载到主机上的目录中。
. 转到包含下载内容的目录。
. 解压缩文件并提取 SAN 工具包软件包。
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
解压缩文件时会创建以下目录： `ntap_aix_host_utilities_6.1` 。此目录将包含以下子目录之一： MPIO ， non_MPIO 或 SAN_Tool_Kit

. 安装 AIX MPIO ：
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. 安装 SAN 工具包：
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. 重新启动主机。
. 验证安装。
+
[source, cli]
----
sanlun version
----




== 下一步是什么？

link:hu-aix-san-toolkit.html["了解 AIX SAN 工具包"] 。
