---
sidebar: sidebar 
permalink: hu_aix_72.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: 介绍如何将 IBM AIX 7.2 和 / 或 PowerVM VIOS 3.1 与 ONTAP 结合使用 
---
= 将IBM AIX 7.2和/或PowerVM (VIOS 3.1)与ONTAP结合使用
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用ONTAP SAN主机配置设置将IBM AIX 7.2和/或PowerVM (VIOS 3.1)配置为目标ONTAP。



== 安装AIX/VIOS主机实用程序

在将AIX MPIO与NetApp ONTAP 存储结合使用时、必须安装AIX主机实用程序套件。

您可以从下载包含 Host Utilities 软件包的压缩文件 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["NetApp 支持站点"^]。获取文件后、您必须对其进行解压缩、以获取安装Host Utilities所需的两个软件包。

NetApp AIX Host Utilities 6.1 是最新版本。此版本可解决先前版本中报告的内存泄漏问题描述。有关追加信息，请参见发行说明部分。

.步骤
. 登录到主机。
+
** 在 AIX 主机上，以 * 根 * 身份登录。
** 在 PowerVM 主机上，以 * padmin* 身份登录，然后输入 `oem_setup_env` 命令以成为 root 。


. 从 NetApp 支持站点将包含 Host Utilities 的压缩文件副本下载到主机上的目录中。
. 转到包含下载内容的目录。
. 解压缩文件并提取 SAN 工具包软件包。
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
解压缩文件时会创建以下目录： `ntap_aix_host_utilities_6.1` 。此目录将包含以下子目录之一： MPIO ， non_MPIO 或 SAN_Tool_Kit

. 安装 AIX MPIO ：
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. 安装 SAN 工具包： `installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`
. 重新启动主机。




== SAN工具包

安装NetApp主机实用程序软件包会自动安装该工具包。此套件提供了 `sanlun`实用程序、可帮助您管理LUN和主机总线适配器(HBA)。命令将 `sanlun`返回有关映射到主机的LUN的信息、多路径以及创建启动程序组所需的信息。

.示例
在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[listing]
----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----


== SAN 启动

.您需要的内容
如果您决定使用 SAN 启动，则配置必须支持它。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^] 验证您的操作系统， HBA ， HBA 固件和 HBA 启动 BIOS 以及 ONTAP 版本是否受支持。

SAN 启动是将 SAN 连接的磁盘（ LUN ）设置为 AIX/PowerVM 主机的启动设备的过程。您可以将 SAN 启动 LUN 设置为在运行采用 FC 或 FCoE 协议的 AIX Host Utilities 的 AIX MPIO 环境中运行。在 AIX MPIO 环境中，用于创建 SAN 启动 LUN 并在其上安装新操作系统映像的方法可能会有所不同，具体取决于您使用的协议。



== 多路径

多路径允许您在主机和存储系统之间配置多个网络路径。如果一个路径发生故障，则流量将继续在其余路径上传输。Host Utilities 的 AIX 和 PowerVM 环境使用 AIX 的原生 Multipathing 解决方案（ MPIO ）。

对于 AIX ，路径控制模块（ PCM ）负责控制多个路径。PCM 是存储供应商提供的用于处理路径管理的代码。在 Host Utilities 安装过程中会安装并启用此功能。



=== 非ASA配置

对于非ASA配置、应具有两组具有不同优先级的路径。优先级较高的路径为主动/优化路径、这意味着它们由聚合所在的控制器提供服务。优先级较低的路径处于活动状态、但未进行优化、因为它们是从其他控制器提供的。只有在优化路径不可用时、才会使用非优化路径。

.示例
以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出。

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----


=== 所有SAN阵列配置

全SAN阵列(ASA)配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

.示例
以下示例显示了ONTAP LUN的正确输出。


NOTE: 从适用于 AIX 主机的 ONTAP 9.8 开始，支持所有 SAN 阵列（ ASA ）配置。

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----


== 建议设置

下面是ONTAP LUN的一些建议参数设置。  安装 ONTAP 主机实用程序套件后，系统会自动设置 NetApp LUN 的关键参数。

[cols="4*"]
|===
| 参数 | environment | AIX 的价值 | 注意 


| 算法 | MPIO | 循环 | 由 Host Utilities 设置 


| hcheck_cmd | MPIO | 查询 | 由 Host Utilities 设置 


| hcheck_interval | MPIO | 30 个 | 由 Host Utilities 设置 


| hcheck_mode | MPIO | 非活动 | 由 Host Utilities 设置 


| lun_reset_st | MPIO / 非 MPIO | 是的。 | 由 Host Utilities 设置 


| max_transfer | MPIO / 非 MPIO | FC LUN ： 0x100000 字节 | 由 Host Utilities 设置 


| QFull | MPIO / 非 MPIO | 2 秒延迟 | 由 Host Utilities 设置 


| queue_depth | MPIO / 非 MPIO | 64 | 由 Host Utilities 设置 


| reserve_policy | MPIO / 非 MPIO | no_reserve | 由 Host Utilities 设置 


| rw_timeout (磁盘) | MPIO / 非 MPIO | 30 秒 | 使用操作系统默认值 


| dyntrk | MPIO / 非 MPIO | 是的。 | 使用操作系统默认值 


| FC_err_recov | MPIO / 非 MPIO | fast_fail | 使用操作系统默认值 


| q_type | MPIO / 非 MPIO | 简单 | 使用操作系统默认值 


| num_cmd_elems | MPIO / 非 MPIO | 对于 AIX 3072 ，对于 VIOS 为 1024 | FC EN1B ， FC EN1C 


| num_cmd_elems | MPIO / 非 MPIO | 1024 （用于 AIX ） | FC EN0G 
|===


== MetroCluster 的建议设置

默认情况下、如果没有LUN的可用路径、则AIX操作系统会强制执行较短的I/O超时。在包括单交换机 SAN 网络结构和发生计划外故障转移的 MetroCluster 配置在内的配置中可能会发生这种情况。有关追加信息 以及对默认设置的建议更改、请参见 link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318["NetApp KB1001318"^]



== AIX支持SnapMirror主动同步

从ONTAP 9.11.1开始、SnapMirror主动同步支持AIX。在AIX配置中、主集群是"活动"集群。

在AIX配置中、故障转移会造成中断。每次故障转移时、您都需要在主机上执行重新扫描、才能恢复I/O操作。

要为AIX配置SnapMirror活动同步、请参阅知识库文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)["如何为SnapMirror活动同步配置AIX主机"^]。



== 已知问题

带有ONTAP版本的IBM AIX 7.2和/或PowerVM (VIOS 3.1)存在以下已知问题：

[cols="4*"]
|===
| NetApp 错误 ID | 标题 | Description | 合作伙伴 ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1416221["1416221."^] | AIX 7200-05-01 在存储故障转移期间遇到虚拟 iSCSI 磁盘（ VIOS 3.1.1.x ）的 I/O 中断 | 在通过 VIOS 3.1.1.x 映射的虚拟 iSCSI 磁盘上的 AIX 7.2 TL5 主机上执行存储故障转移操作期间，可能会发生 I/O 中断默认情况下， VIOC 上虚拟 iSCSI 磁盘（ hdisk ）的 `rw_timeout` 值将为 45 秒。如果在存储故障转移期间发生超过 45 秒的 I/O 延迟，则可能会发生 I/O 故障。要避免这种情况，请参见 BURT 中所述的临时解决策。根据 IBM 的要求，在应用 APAR - IJ34739 （即将发布的版本）后，我们可以使用 `chdev` 命令动态更改 rw_timeout 值。 | 不适用 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1414700["1414700"^] | 在存储故障转移期间， AIX 7.2 TL04 的虚拟 iSCSI 磁盘（ VIOS 3.1.1.x ）发生 I/O 中断 | 在通过 VIOS 3.1.1.x 映射的虚拟 iSCSI 磁盘上的 AIX 7.2 TL4 主机上执行存储故障转移操作期间，可能会发生 I/O 中断默认情况下， VIOC 上 vSCSI 适配器的 `rw_timeout` 值为 45 秒。如果在存储故障转移期间发生超过 45 秒的 I/O 延迟，则可能会发生 I/O 故障。要避免这种情况，请参见 BURT 中所述的临时解决策。 | 不适用 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1307653["1307653"^] | 在 SFO 故障和直连 I/O 期间发现 VIOS 3.1.1.10 上的 I/O 问题 | 在 VIOS 3.1.1 上，由 16/32 Gb FC 适配器提供支持的 NPIV 客户端磁盘可能会出现 IO 故障。此外， `vfchost` 驱动程序可能会进入停止处理来自客户端的 I/O 请求的状态。应用 IBM APAR IJ22290IBM APAR IJ23222 可修复问题描述 | 不适用 
|===