---
sidebar: sidebar 
permalink: hu_aix_71.html 
keywords: host utilities, aix, 7.1 netapp, ontap 
summary: 介绍如何将 IBM AIX 7.1 与 ONTAP 结合使用 
---
= 将 IBM AIX 7.1 与 NetApp ONTAP 结合使用
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== 安装 AIX Host Utilities

在将 AIX MPIO 与 NetApp ONTAP 存储结合使用时，必须安装 AIX 主机实用程序套件。

您可以从 NetApp 支持站点下载包含 Host Utilities 软件包的压缩文件。获取此文件后，您必须将其解压缩，以获取安装 Host Utilities 所需的两个软件包。

.步骤
. 登录到主机。
+
** 在 AIX 主机上，以 * 根 * 身份登录。


. 从 NetApp 支持站点将包含 Host Utilities 的压缩文件副本下载到主机上的目录中。
. 转到包含下载内容的目录。
. 解压缩文件并提取 SAN 工具包软件包。
+
`zcat ntap_aix_host_utilities_6.0.tar.Z` tar -xvf –

+
解压缩文件时会创建以下目录： `ntap_aix_host_utilities_6.0` 。此目录将包含以下子目录之一： MPIO ， non_MPIO 或 SAN_Tool_Kit

. 安装 AIX MPIO ：
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. 安装 SAN 工具包： `installp -aXYd /var/tmp/ntap_aix_host_utilities_6.0/SAN_Tool_Kit netapp.SAN_toolkit`
. 重新启动主机。




== SAN 工具包

安装 NetApp Host Utilities 软件包时，工具包会自动安装。此套件提供 `sanlun` 实用程序，可帮助您管理 LUN 和 HBA 。`sanlun` 命令可返回有关映射到主机的 LUN 的信息，多路径以及创建启动程序组所需的信息。

在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[listing]
----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----


== SAN 启动

如果您决定使用 SAN 启动，则配置必须支持它。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^] 验证您的操作系统， HBA ， HBA 固件和 HBA 启动 BIOS 以及 ONTAP 版本是否受支持。

SAN 启动是将 SAN 连接的磁盘（ LUN ）设置为 AIX 主机的启动设备的过程。您可以将 SAN 启动 LUN 设置为在运行采用 FC 或 FCoE 协议的 AIX Host Utilities 的 AIX MPIO 环境中运行。在 AIX MPIO 环境中，用于创建 SAN 启动 LUN 并在其上安装新操作系统映像的方法可能会有所不同，具体取决于您使用的协议。



== 多路径

多路径允许您在主机和存储系统之间配置多个网络路径。如果一个路径发生故障，则流量将继续在其余路径上传输。Host Utilities 的 AIX 环境使用 AIX 原生多路径解决方案， MPIO 。

对于 AIX ，路径控制模块（ PCM ）负责控制多个路径。PCM 是存储供应商提供的用于处理路径管理的代码。在 Host Utilities 安装过程中会安装并启用此功能。



=== Non-ASA 配置

对于非 ASA 配置，应存在两组具有不同优先级的路径。优先级较高的路径为主动 / 优化路径，这意味着它们由聚合所在的控制器提供服务。优先级较低的路径处于活动状态，但未进行优化，因为它们是从其他控制器提供的。只有在没有优化路径可用时，才会使用非优化路径。

以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出：

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----


=== 全 SAN 阵列配置

在所有 SAN 阵列（ ASA ）配置中，指向给定逻辑单元（ LUN ）的所有路径均处于活动状态并已进行优化。这意味着可以同时通过所有路径提供 I/O ，从而提高性能。

以下示例显示了 ONTAP LUN 的正确输出：


NOTE: 从适用于 AIX 主机的 ONTAP 9.8 开始，支持所有 SAN 阵列（ ASA ）配置。

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----


== 建议设置

以下是为 NetApp ONTAP LUN 建议的一些参数设置。安装 ONTAP 主机实用程序套件后，系统会自动设置 NetApp LUN 的关键参数。

[cols="4*"]
|===
| 参数 | environment | AIX 的价值 | 注意 


| 算法 | MPIO | 循环 | 由 Host Utilities 设置 


| hcheck_cmd | MPIO | 查询 | 由 Host Utilities 设置 


| hcheck_interval | MPIO | 30 个 | 由 Host Utilities 设置 


| hcheck_mode | MPIO | 非活动 | 由 Host Utilities 设置 


| lun_reset_st | MPIO / 非 MPIO | 是的。 | 由 Host Utilities 设置 


| max_transfer | MPIO / 非 MPIO | FC LUN ： 0x100000 字节 | 由 Host Utilities 设置 


| QFull | MPIO / 非 MPIO | 2 秒延迟 | 由 Host Utilities 设置 


| queue_depth | MPIO / 非 MPIO | 64 | 由 Host Utilities 设置 


| reserve_policy | MPIO / 非 MPIO | no_reserve | 由 Host Utilities 设置 


| re_timeout （磁盘） | MPIO / 非 MPIO | 30 秒 | 使用操作系统默认值 


| dyntrk | MPIO / 非 MPIO | 是的。 | 使用操作系统默认值 


| FC_err_recov | MPIO / 非 MPIO | fast_fail | 使用操作系统默认值 


| q_type | MPIO / 非 MPIO | 简单 | 使用操作系统默认值 


| num_cmd_elems | MPIO / 非 MPIO | 1024 （用于 AIX ） | FC EN1B ， FC EN1C 


| num_cmd_elems | MPIO / 非 MPIO | 500 （用于 AIX ）（独立 / 物理） 200 （用于 VIOC ） | FC EN0G 
|===


== MetroCluster 的建议设置

默认情况下，如果 LUN 的路径不可用，则 AIX 操作系统会强制执行较短的 I/O 超时。在包括单交换机 SAN 网络结构和发生计划外故障转移的 MetroCluster 配置在内的配置中可能会发生这种情况。有关追加信息以及对默认设置的建议更改，请参见 link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318["NetApp KB1001318"]



== 已知问题和限制

没有已知问题和限制。
