---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: 介绍如何使用 AIX 发现和配置 LUN 
---
= （不使用 PowerVM 的 AIX MPIO ）使用 AIX 发现和配置 LUN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果在不使用 PowerVM 的情况下使用 AIX ，则可以使用 cfgmgr 命令使主机发现 LUN 。您无需重新启动主机即可发现 LUN 。要确认主机是否发现了 LUN ，您可以使用 sanlun 实用程序。


NOTE: 以下步骤不适用于运行 PowerVM 环境的主机。

.步骤
. 以 root 身份登录到主机。
. 在 AIX 主机上，输入以下命令以发现新创建的 LUN ：
+
`cfgmgr`

+
`cfgmgr` 命令有助于实现以下功能：

+
** 用于登录到网络结构的启动程序。
** 要检查新设备的系统。
** 系统以创建新设备条目。


. 要显示所有 AIX 磁盘，包括 NetApp LUN ，请输入以下命令：
+
`lsdev -CC disk`

+
LUN 在主机上显示为磁盘。这些磁盘的使用方式与在主机上使用本地磁盘的方式相同。如果在 Host Utilities 中安装了主机设置 ODM 文件，则这些 LUN 将显示为 NetApp FCP 磁盘。

+
记下 hdisk 实例编号。您可以在执行路径配置时使用它们。

+
以下是 lsdev -CC disk 命令在使用 FC 的环境中生成的输出类型。

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. 输入以下命令以获取有关设置的信息：
+
`lsattr -EL hdisk_name`

+
此命令将生成以下输出。

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. 如果您的配置支持 ALUA ，则可以使用它来设置路径优先级。验证是否已启用 ALUA ：
+
`lun igroup show -instance igroup_name`

+
.. 如果未启用 ALUA ，请启用它：
+
`igroup set igroup_name ALUA yes`



. 如果您的配置不支持 ALUA ，则必须执行 dotpaths 实用程序来设置路径优先级。dotpaths 实用程序会在您安装 Host Utilities 时安装。如果已启用 ALUA ，请勿使用 dotpaths 实用程序。
+
.. 要设置所有 Data ONTAP LUN 的优先级，请输入：
+
`dotpaths`

.. 要设置一组特定磁盘的优先级，请输入：
+
`dotpaths [-hv] [hdiskN ...]`

+
使用 ` -v` 选项启用详细模式并显示所有优先级。使用 ` -q` 选项查询所有或单个磁盘优先级。



. 要验证主机是否已发现 LUN ，请输入以下命令：
+
` # sanlun lun show`

+
.示例
此示例显示了 MPIO 多路径环境中 `sanlun lun show` 命令的典型输出。

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

