---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: 介绍如何将 Citrix XenServer 7.x 与 ONTAP 结合使用 
---
= 将Citrix XenServer与ONTAP结合使用
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以为使用FC、FCoE和iSCSI协议的Citrix XenServer 7系列操作系统版本配置ONTAP SAN主机配置设置。



== SAN 启动

.您需要的内容
如果您决定使用 SAN 启动，则配置必须支持它。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp 互操作性表工具"^] 验证您的操作系统， HBA ， HBA 固件和 HBA 启动 BIOS 以及 ONTAP 版本是否受支持。

.步骤
. 将 SAN 启动 LUN 映射到主机。
. 验证是否有多个可用路径。
+

NOTE: 主机操作系统启动并在多个路径上运行后、这些路径将变为可用。

. 在服务器 BIOS 中为 SAN 启动 LUN 映射到的端口启用 SAN 启动。
+
有关如何启用 HBA BIOS 的信息，请参见供应商专用文档。

. 重新启动主机以验证启动是否成功。




== 多路径

Citrix XenServer 中的多路径支持基于设备映射程序多路径组件。不会自动为呈现给 XenServer 的所有 LUN 创建设备映射器节点，并且只有在存储管理层（ API ）正在使用 LUN 时才会配置设备映射器节点。Citrix XenServer Storage Manager API 插件可自动激活和停用多路径节点。

由于与集成多路径管理架构不兼容， Citrix 建议您使用 Citrix XenCenter 应用程序管理存储配置。如果需要手动查询设备映射程序表的状态或列出系统上的活动设备映射程序多路径节点，可以使用 ` /sbin/mpathutil status` 命令验证 ONTAP LUN 的设置。有关详细信息，请参阅 Citrix XenServer 的标准供应商文档。



=== Non-ASA 配置

对于非ASA配置、应具有两组具有不同优先级的路径。优先级较高的路径为主动 / 优化路径，这意味着它们由聚合所在的控制器提供服务。优先级较低的路径处于活动状态，但未进行优化，因为它们是从其他控制器提供的。只有在没有优化路径可用时，才会使用非优化路径。

.示例
以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出：

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: 请勿使用过多的路径访问单个 LUN 。所需路径不应超过四个。在存储故障期间，超过八个路径可能会出现发生原因路径问题。



=== 全 SAN 阵列配置

在所有 SAN 阵列（ ASA ）配置中，指向给定逻辑单元（ LUN ）的所有路径均处于活动状态并已进行优化。这意味着可以同时通过所有路径提供 I/O ，从而提高性能。

.示例
以下示例显示了具有所有四个主动/优化路径的ONTAP LUN的正确输出：

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: 请勿使用过多的路径访问单个 LUN 。所需路径不应超过四个。在存储故障期间，超过八个路径可能会出现发生原因路径问题。



=== 建议设置

Citrix XenServer 7.x 操作系统会使用识别和正确管理 ONTAP LUN 所需的所有设置进行编译。对于 Citrix XenServer 7.x ，必须存在空的 zerobyte ` /etc/multipath.conf` 文件，但您不需要对该文件进行特定更改。

从 * XenCenter 管理门户 * 启用主机多路径服务，并验证多路径服务是否已启用且正在运行。

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
不需要将内容附加到 ` /etc/multipath.conf` 文件，除非您的设备不希望由多路径管理，或者您的现有设置覆盖默认值。您可以将以下语法添加到 `multipath.conf` 文件中，以排除不需要的设备。

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: 将 * <DevID>* 替换为要排除的设备的 WWID 字符串。

.示例
在本示例中、对于Citrix XenServer 7.x、 `sda` 是需要添加到黑名单中的本地SCSI磁盘。

. 运行以下命令以确定 WWID ：
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. 将此 WWID 添加到 ` /etc/multipath.conf` 中的黑名单 stanza 中：
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


使用 ` $multipathd show config` 命令查看多路径参数运行时配置。您应始终检查正在运行的配置中是否存在可能会覆盖默认设置的旧设置，尤其是在默认设置部分。

下表显示了 ONTAP LUN 的关键 * 多路径 * 参数以及所需值。如果某个主机已连接到其他供应商的 LUN ，并且这些参数中的任何一个被覆盖，则需要在专门适用于 ONTAP LUN 的 * multipath.conf* 中使用稍后的 stantzas 进行更正。如果不执行此操作， ONTAP LUN 可能无法按预期工作。只有在与 NetApp 和 / 或操作系统供应商协商后，才能覆盖以下默认值，并且只有在完全了解其影响时才会覆盖这些默认值。

[cols="2*"]
|===
| 参数 | 正在设置 ... 


| `detect_prio` | 是的。 


| `dev_los_TMOs` | " 无限 " 


| `故障恢复` | 即时 


| `fast_io_fail_sm` | 5. 


| `功能` | "3 queue_if_no_path pG_init_retries 50" 


| `flush_on_last_del` | 是的。 


| `hardware_handler` | 0 


| `path_checker` | "TUR" 


| `path_grouping_policy` | "Group_by-prio" 


| `path_selector` | " 服务时间 0" 


| `Polling _interval` | 5. 


| `prio` | ONTAP 


| `产品` | lun.* 


| `retain Attached _hw_handler` | 是的。 


| `rr_weight` | " 统一 " 


| `user_friendly_names` | 否 


| `vendor` | NetApp 
|===
.示例
以下示例说明了如何更正被覆盖的默认值。在这种情况下， * 多路径 .conf * 文件定义了与 ONTAP LUN 不兼容的 * 路径检查程序 * 和 * 检测 _prio* 值。如果由于连接到主机的其他 SAN 阵列而无法删除这些参数，则可以专门针对具有设备实例的 ONTAP LUN 更正这些参数。

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: 对于支持的配置， Citrix XenServer 建议对所有基于 Linux 和 Windows 的子虚拟机使用 Citrix VM 工具。



== 已知问题和限制

没有已知问题和限制。
