---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 介绍如何在ONTAP中使用HP-UX Unified Host Utilities 6.0 
---
= HP-UX Host Utilities 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
使用HP-UX Host Utilities可以将HP-UX主机连接到NetApp存储。

HP-UX Host Utilities支持多个HP-UX环境和多个协议。以下是支持的环境：

* 原生 MPIO
* Veritas动态多路径(DMP)



NOTE: 为了指明所使用的环境、本文档有时会为Veritas DMP环境指定"DMP"、为HP-UX本机环境指定"MPIO"。在某些情况下、您使用的命令可能会因所使用的驱动程序而异。在这些情况下、系统会同时指定环境和驱动程序类型。

.您需要的内容
* 为了确保操作可靠、请验证您的整个iSCSI、FC或FCoE配置是否受支持。


您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^] 以验证您的配置。

.关于此任务
上提供了NetApp HP-UX Host Utilities软件包 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.0/downloads["NetApp 支持站点"^] 在压缩文件中。下载文件后，必须在安装之前对其进行解压缩。

.步骤
. 登录到主机。
. 从下载 HP-UX Host Utilities 文件 `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` link:https://mysupport.netapp.com/site/["NetApp 支持站点"^] 连接到 HP-UX 主机。
. 解压 `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` 文件：
+
` # gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
系统会将提取的软件放置在解压缩存储库文件的目录中。

. 安装软件：
+
` # swinstall -s /storage_path`

+
`dept_path` 提供存储库文件的路径和名称。

+
`swinstall` 命令可运行一个安装脚本，用于验证 HP-UX 设置的状态。如果您的系统满足要求，此脚本会将 `sanlun` 实用程序和诊断脚本安装在 ` /opt/netapp/santools/bin` 目录中。

. 验证安装。
+
`sanlun 版本`





== SAN 工具包

HP-UX Host Utilities是一款NetApp主机软件、可在HP-UX主机上提供命令行工具包。此工具包会在您安装 NetApp Host Utilities 软件包时安装。此套件提供 `sanlun` 实用程序，可帮助您管理 LUN 和 HBA 。`sanlun` 命令可返回有关映射到主机的 LUN 的信息，多路径以及创建启动程序组所需的信息。

.示例
在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: 此工具包在 Host Utilities 的所有配置和协议中通用。因此，其中某些内容适用于一种配置，而不适用于另一种配置。未使用的组件不会影响系统性能。
