---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 介绍如何在ONTAP中使用Linux主机实用程序7.1 
---
= 安装Linux Host Utilities 7.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
"Linux Host Utilities (Linux主机实用程序)"可帮助您管理连接到Linux主机的ONTAP存储。NetApp强烈建议安装Linux主机实用程序、但并非强制要求。这些实用程序不会更改 Linux 主机上的任何设置。这些实用程序可改进管理并帮助 NetApp 客户支持收集有关您的配置的信息。

支持以下Linux分发版：

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Oracle VM
* Citrix XenServer


.开始之前
NetApp LINUX主机实用程序软件包以32位或64位.rpm文件的形式在上提供link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^]。

* 为了确保操作可靠，您必须验证您的整个 iSCSI ， FC 或 FCoE 配置是否受支持。
+
您可以使用link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]验证配置。

* 您必须安装供应商支持站点上提供的主机总线适配器(HBA)管理软件包。
+
通过管理软件、SAN Toolkit命令可以收集有关FC HBA的信息、例如其WWPN。要使 `sanlun fcp show adapter`命令正常运行、请验证是否已正确安装以下软件包：

+
** Marvell QLogic HBA—QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand Manager核心应用程序CLI
** Marvell Brocade HBA—Brocade命令实用程序CLI


* 每个Linux分发版都可用的RPM软件包"libhbaapi"和"libhbalinux"应安装在主机操作系统上。



NOTE: Linux Host Utilities软件不支持基于光纤通道的NVMe (NVMe/FC)和基于TCP的NVMe (NVMe/TCP)主机协议。

.步骤
. 如果您当前安装的是Linux Host Utilities版本、请使用以下命令将其删除：
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
对于早期版本的Linux Host Utilities、请转到安装主机实用程序软件的目录、然后输入uninstall命令以删除已安装的软件包。

. 将32位或64位Linux Host Utilities软件包从下载link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^]到主机。
. 转到软件包下载到的目录，然后使用以下命令进行安装：
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. 验证安装。
+
[source, cli]
----
sanlun version
----
+
[listing]
----
sanlun version 7.1.386.1644
----




== Linux内核的建议驱动程序设置

如果您配置的FC环境使用Linux内核捆绑的本机收件箱驱动程序、则可以使用这些驱动程序的默认值。



== SAN 工具包

Linux Host Utilities是NetApp主机软件、可在Linux主机上提供命令行工具包。

安装 NetApp Host Utilities 软件包时，工具包会自动安装。此套件提供 `sanlun` 实用程序，可帮助您管理 LUN 和 HBA 。`sanlun` 命令可返回有关映射到主机的 LUN 的信息，多路径以及创建启动程序组所需的信息。

.示例
在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[source, cli]
----
# sanlun lun show all
----
示例输出：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* 此工具包在 Host Utilities 的所有配置和协议中通用。因此，其中某些内容适用于一种配置，而不适用于另一种配置。未使用的组件不会影响系统性能。
* Citrix XenServer、Oracle VM和Red Hat Enterprise Virtualization Hypervisor"不支持SAN工具包"。


====