---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 介绍如何在ONTAP中使用Linux主机实用程序7.1 
---
= 为ONTAP存储安装 Linux Host Utilities 7.1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilities 可帮助您管理连接到 Linux 主机的ONTAP存储。 NetApp强烈建议安装 Linux Host Utilities，但这不是强制性的。这些实用程序可改善管理并帮助NetApp客户支持收集有关您的配置的信息。

Linux Host Utilities 7.1 支持以下分发类型：

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Oracle VM
* Citrix XenServer



NOTE: Linux Host Utilities软件不支持基于光纤通道的NVMe (NVMe/FC)和基于TCP的NVMe (NVMe/TCP)主机协议。

.关于此任务
当您安装 Linux 主机实用程序时，它不会更改 Linux 主机上的任何设置。

.开始之前
* 为了可靠运行，使用link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的 iSCSI、FC 或 FCoE 配置是否受支持。
* 安装供应商支持站点上提供的主机总线适配器 (HBA) 管理包。管理软件可实现 `sanlun`命令来收集有关 FC HBA 的信息，例如其 WWPN。
+
请参阅供应商文档来验证以下软件包是否正确安装。这些软件包需要支持 `sanlun fcp show adapter`命令：

+
** Marvell QLogic HBA—QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand Manager核心应用程序CLI
** Marvell Brocade HBA—Brocade命令实用程序CLI


* 在 Linux 主机操作系统上安装适用于每个 Linux 发行版的 RPM“libhbaapi”和“libhbalinux”包。


.步骤
. 如果您当前安装了某个版本的 Linux Host Utilities，请将其删除：
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
对于早期版本的Linux Host Utilities、请转到安装主机实用程序软件的目录、然后输入uninstall命令以删除已安装的软件包。

. 将32位或64位Linux Host Utilities软件包从下载link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^]到主机。
. 进入下载软件包的目录并安装：
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
您应该会看到类似于以下示例的输出：

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. 验证安装。
+
[source, cli]
----
sanlun version
----
+
您应该会看到类似于以下示例的输出：

+
[listing]
----
sanlun version 7.1.386.1644
----




== 下一步是什么？

* Linux内核的建议驱动程序设置
+
如果您配置的FC环境使用Linux内核捆绑的本机收件箱驱动程序、则可以使用这些驱动程序的默认值。

* link:hu-luhu-sanlun-utility.html["了解“三仑”实用程序"] 。

