---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: 《Linux Host Utilities 7.1发行说明》 
---
= 《Linux Host Utilities 7.1发行说明》
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本发行说明介绍了有关使用ONTAP存储系统配置和管理特定主机的新增功能和增强功能、已知问题和限制以及重要注意事项。

有关Host Utilities支持的操作系统版本和更新的特定信息，请参阅link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]。



== 新增功能

Linux Host Utilities 7.1版包含以下新增功能和增强功能：

* Linux Host Utilities现在称为_Linux Unified Host Utilities _、因为它支持运行SANtricity的NetApp E系列存储系统以及运行ONTAP的AFF、FAS和ASA系统。
+

NOTE: 本文档中提及的Host Utilities或Linux Host Utilities均指Linux Unified Host Utilities。

* 现在支持以下操作系统：
+
** SUSE Linux Enterprise Server 15系列
** Oracle VM 3.2系列
** Oracle Linux 6和7系列
** Red Hat Enterprise Linux 6和7系列
** SUSE Linux Enterprise Server 11 SP4
** KVM和XEN、RHEV-6.4和6.5
** Citrix XenServer


* 在Red Hat Enterprise Linux (RHEL) 6和RHEL 7主机上、现在支持一个经过调整的软件包、用于设置服务器配置文件。您可以使用 `tuned-adm` 命令以根据环境设置不同的配置文件。例如、您还可以将虚拟子系统配置文件用作子虚拟机、并将企业存储配置文件用于使用企业存储阵列中的LUN的配置。使用这些经过调整的软件包可以提高ONTAP的吞吐量和延迟。
* 增加了对Broadcom Emulex和Marvell Qlogic中32 Gb FC适配器的支持。



NOTE: 在初始版本之后、NetApp将继续与Host Utilities配合使用、以增加对功能的支持。有关支持的功能和新增功能link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]的最新信息，请参见。



== 此版本已修复

此版本修复了在SUSE Linux Enterprise Server 12 SP1、OL 7.2、RHEL 7.2和RHEL 6.8中运行命令时出现的间歇性主机操作系统故障问题 `sanlun lun show -p`。



== 已知问题和限制

Linux Host Utilities 7.1版具有以下已知问题和限制。

[cols="10, 30, 30"]
|===
| NetApp 错误 ID | 标题 | Description 


| 1457017 | `sanlun`安装问题与`libdevmapper.so`和`libnl.so`库相关的警告消息。这些警告不会影响`sanlun` kit的功能。 | 在SAN主机上执行Linux主机实用程序命令行界面命令sanlun fcp show adapter -v"时，该命令失败，并显示一条错误消息，显示找不到主机总线适配器(Host Bus Adapter, HBA)发现所需的库依赖关系：
`[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded`请参阅NetApp错误在线-link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^]。 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bug Online"^] 提供有关大多数已知问题的完整信息、包括可能的建议解决方法。
