---
sidebar: sidebar 
permalink: hu_ol_74.html 
keywords: host utilities, oracle, linux, 7.4, netapp, ontap 
summary: 介绍如何在 ONTAP 中使用 Oracle Linux 7.4 
---
= 将Oracle Linux 7.4与ONTAP结合使用
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用ONTAP SAN主机配置设置将以ONTAP为目标的Oracle Linux 7.4配置为目标。



== 安装 Linux Unified Host Utilities

上提供了 NetApp Linux Unified Host Utilities 软件包 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^] 在 32 位和 64 位 .rpm 文件中。如果您不知道哪个文件适合您的配置，请使用 link:https://mysupport.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^] 验证所需的配置。

NetApp强烈建议安装Linux统一主机实用程序、但并非强制要求。这些实用程序不会更改 Linux 主机上的任何设置。这些实用程序可改进管理并帮助 NetApp 客户支持收集有关您的配置的信息。

如果您当前安装的是Linux Unified Host Utilities版本、则应将其升级或删除、然后按照以下步骤安装最新版本。

.步骤
. 从下载 32 位或 64 位 Linux Unified Host Utilities 软件包 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^] 站点到主机。
. 使用以下命令安装软件包：
+
`rpm -ivh netapp_linux_unified_host_utilitis-7-1.x86_64`




NOTE: 您可以使用本文档中提供的配置设置来配置连接到的云客户端 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] 和 link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["适用于 ONTAP 的 Amazon FSX"^]。



== SAN 工具包

安装 NetApp Host Utilities 软件包时，工具包会自动安装。此套件提供 `sanlun` 实用程序，可帮助您管理 LUN 和 HBA 。`sanlun` 命令可返回有关映射到主机的 LUN 的信息，多路径以及创建启动程序组所需的信息。

.示例
在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[source, cli]
----
# sanlun lun show all
----
示例输出：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN 启动

.您需要的内容
如果您决定使用 SAN 启动，则配置必须支持它。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=80004;&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^] 验证您的操作系统， HBA ， HBA 固件和 HBA 启动 BIOS 以及 ONTAP 版本是否受支持。

.步骤
. 将 SAN 启动 LUN 映射到主机。
. 验证是否有多个可用路径。
+

NOTE: 主机操作系统启动并在多个路径上运行后、这些路径将变为可用。

. 在服务器 BIOS 中为 SAN 启动 LUN 映射到的端口启用 SAN 启动。
+
有关如何启用 HBA BIOS 的信息，请参见供应商专用文档。

. 重新启动主机以验证启动是否成功。




== 多路径

对于 Oracle Linux 7.4 ， /etc/multipath.conf 文件必须存在，但您不需要对该文件进行特定更改。Oracle Linux 7.4 使用识别和正确管理 ONTAP LUN 所需的所有设置进行编译。

您可以使用 `multipath -ll`命令验证ONTAP LUN的设置。应存在两组具有不同优先级的路径。优先级较高的路径为主动/优化路径、这意味着它们由聚合所在的控制器提供服务。优先级较低的路径处于活动状态、但未进行优化、因为它们是从其他控制器提供的。只有在优化路径不可用时、才会使用非优化路径。

.示例
以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出：

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: 一个LUN不应需要四个以上的路径。如果路径数超过四个、则可能会在存储故障期间导致路径问题。



== 建议设置

经过编译的Oracle Linux 7.4操作系统可识别ONTAP LUN并自动正确设置所有配置参数。 `multipath.conf`要启动多路径守护进程、必须存在该文件。如果此文件不存在、您可以使用命令创建一个空的零字节文件 `touch /etc/multipath.conf`

首次创建 `multipath.conf`文件时、可能需要使用以下命令启用并启动多路径服务：

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

您无需直接向文件中添加任何内容 `multipath.conf`、除非您的设备不需要多路径管理、或者您的现有设置会覆盖默认值。要排除不需要的设备、请在 `multipath.conf`文件中添加以下语法、将<DevId>替换为要排除的设备的WWID字符串：

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
以下示例将确定设备的WWID并将其添加到文件中 `multipath.conf`。

.步骤
. 确定WWID：
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda`是要添加到黑名单中的本地SCSI磁盘。

. 添加 `WWID` 到黑名单中 `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


您应始终检查 `/etc/multipath.conf`文件、尤其是在默认部分中、以了解可能会覆盖默认设置的原有设置。

下表显示了ONTAP LUN的关键 `multipathd`参数以及所需设置。如果主机连接到其他供应商的LUN、并且这些参数中的任何一个被覆盖、则必须通过 `multipath.conf`文件中专门适用于ONTAP LUN的后续条款进行更正。如果不进行此更正、ONTAP LUN可能无法按预期运行。只有在与NetApp和/或操作系统供应商协商后、并且只有在充分了解影响后、才应覆盖这些默认值。

[cols="2*"]
|===
| 参数 | 正在设置 ... 


| detect_prio | 是的。 


| dev_los_TMO | " 无限 " 


| 故障恢复 | 即时 


| fast_io_fail_sMO | 5. 


| features | "3 queue_if_no_path pG_init_retries 50" 


| flush_on_last_del | 是的。 


| 硬件处理程序 | 0 


| path_checker | "TUR" 


| path_grouping_policy | "Group_by-prio" 


| path_selector | " 服务时间 0" 


| Polling interval | 5. 


| PRIO | ONTAP 


| 产品 | lun.* 


| Retain Attached Hw_handler | 是的。 


| rr_weight | " 统一 " 


| user_friendly_names | 否 


| 供应商 | NetApp 
|===
.示例
以下示例显示了如何更正被覆盖的默认值。在这种情况下， `multipath.conf` 文件会为 `path_checker` 和 `detect_prio` 定义与 ONTAP LUN 不兼容的值。如果由于其他 SAN 阵列仍连接到主机而无法删除这些参数，则可以专门针对具有设备实例的 ONTAP LUN 更正这些参数。

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: 要配置Oracle Linux 7.4 Red Hat Enterprise Kernel (RHCK)、请使用link:hu_rhel_74.html#recommended-settings["建议设置"]适用于Red Hat Enterprise Linux (RHEL) 7.4的。



== 已知问题

具有ONTAP版本的Oracle Linux 7.4存在以下已知问题：

[cols="3*"]
|===
| NetApp 错误 ID | 标题 | Description 


| 1440718 | 如果在未执行SCSI重新扫描的情况下取消映射或映射LUN、可能会导致主机上的数据损坏。 | 如果将"disable_changed_WWIDs"多路径配置参数设置为是、则在WWID发生更改时、它将禁用对路径设备的访问。在将路径的WWID还原到多路径设备的WWID之前、多路径将禁用对路径设备的访问。要了解更多信息，请参见 link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp知识库：Oracle Linux 7上iSCSI LUN上的文件系统损坏"^]。 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1109468["1109468"^] | 在使用 QLE8362 卡的 OL7.4 虚拟机管理程序上观察到固件转储 | 在使用 QLE8362 卡的 OL7.4 虚拟机管理程序上执行存储故障转移操作期间，偶尔会观察到固件转储。固件转储可能会导致主机上的 I/O 中断，这可能长达 500 秒。适配器完成固件转储后， I/O 操作将以正常方式恢复。主机上不需要进一步的恢复操作步骤。要指示固件转储， /var/log/message 文件中会显示以下消息： qla2xxx [0000 ： 0c ： 00.3]-d001 ： 8 ：固件转储保存到临时缓冲区（ 8/ffc90008901000 ），转储状态标志（ 0x3f ） 
|===