---
sidebar: sidebar 
permalink: hu_ol_88.html 
keywords: host utilities, oracle, linux, 8.8, netapp, ontap 
summary: 介绍如何将Oracle Linux 8.8与ONTAP结合使用 
---
= 将Oracle Linux 8.8与ONTAP结合使用
:hardbreaks:
:toclevels: 1P
:allow-uri-read: 
:toclevels: 1P
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用ONTAP SAN主机配置设置将使用ONTAP的Oracle Linux 8.8配置为目标。



== 安装 Linux Unified Host Utilities

您可以从下载64-bit.rpm文件格式的NetApp Linux统一主机实用程序软件包link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^]。

NetApp强烈建议安装Linux统一主机实用程序、但并非强制要求。这些实用程序不会更改 Linux 主机上的任何设置。这些实用程序可改进管理并帮助 NetApp 客户支持收集有关您的配置的信息。

.步骤
. 从下载 64 位 Linux Unified Host Utilities 软件包 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^] 主机。
. 安装软件包：
+
`rpm -ivh netapp_linux_unified_host_utilitis-7-1.x86_64`





== SAN工具包

安装NetApp主机实用程序软件包时会自动安装该工具包。此套件提供 `sanlun` 实用程序、可帮助您管理LUN和主机总线适配器(HBA)。。 `sanlun` 命令将返回有关映射到主机的LUN的信息、多路径以及创建启动程序组所需的信息。

在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[listing]
----
# sanlun lun show all
----
.示例输出：
[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       80.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       80.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       80.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       80.0g  cDOT
----


== SAN 启动

.您需要的内容
如果您决定使用 SAN 启动，则配置必须支持它。您可以使用 link:https://mysupport.netapp.com/matrix/imt.jsp?components=91863;&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^] 验证您的操作系统， HBA ， HBA 固件和 HBA 启动 BIOS 以及 ONTAP 版本是否受支持。

.步骤
. 将 SAN 启动 LUN 映射到主机。
. 验证是否有多个可用路径。
+

NOTE: 在主机操作系统启动并运行多个路径后、这些路径将变为可用。

. 在服务器 BIOS 中为 SAN 启动 LUN 映射到的端口启用 SAN 启动。
+
有关如何启用 HBA BIOS 的信息，请参见供应商专用文档。

. 重新启动主机以验证启动是否成功。




== 多路径

对于Oracle Linux (OL) 8.8、请使用 `/etc/multipath.conf` 文件必须存在、但您不需要对文件进行特定更改。OL 8.8包含识别和正确管理ONTAP LUN所需的所有设置。

您可以使用 `multipath -ll` 命令验证 ONTAP LUN 的设置。

以下各节提供了映射到ASA和非ASA配置的LUN的多路径输出示例。



=== 所有SAN阵列配置

全SAN阵列(ASA)配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

.示例
以下示例显示了ONTAP LUN的正确输出。

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----

NOTE: 一个LUN不应需要四个以上的路径。如果路径数超过四个、则可能会在存储故障期间导致路径问题。



=== 非ASA配置

对于非ASA配置、应具有两组具有不同优先级的路径。优先级较高的路径为主动/优化路径、这意味着它们由聚合所在的控制器提供服务。优先级较低的路径处于活动状态、但未进行优化、因为它们是从其他控制器提供的。只有在优化路径不可用时、才会使用非优化路径。

.示例
以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出。

[listing]
----
# multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----

NOTE: 一个LUN不应需要四个以上的路径。如果路径数超过四个、则可能会在存储故障期间导致路径问题。



== 建议设置

经过编译的OL 8.8操作系统可识别ONTAP LUN、并自动为ASA和非ASA配置正确设置所有配置参数。您可以使用以下建议设置进一步优化主机配置的性能。

 `multipath.conf`要启动多路径守护进程、必须存在该文件。如果此文件不存在、您可以使用命令创建一个空的零字节文件 `touch /etc/multipath.conf`。

首次创建 `multipath.conf`文件时、可能需要使用以下命令启用并启动多路径服务：

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
您无需直接向文件中添加任何内容 `multipath.conf`、除非您的设备不需要多路径管理、或者您的现有设置会覆盖默认值。要排除不需要的设备、请在文件中添加以下语法 `multipath.conf`、将<DevId>替换为要排除的设备的全球通用标识符(WWID)字符串：

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
以下示例将确定设备的WWID并将其添加到文件中 `multipath.conf`。

.步骤
. 确定WWID：
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
/lib/udev/scsi_id -gud /dev/sda
----
+
360030057024d0730239134810c0cb833



[listing]
----
+
`sda` is the local SCSI disk that you want to add to the blacklist.

. Add the `WWID` to the blacklist stanza in `/etc/multipath.conf`:
[source,cli]
+
----
黑名单{ wwid 3600a098038314c4a433f5774717a3046 devnode "^(ram|raw|lo|fd|m|dm-|sr|scd|st)[0-9]*" devnode "^hd[a-z]" devnode "^cciss.*"｝

[listing]
----

Always check your `/etc/multipath.conf` file, especially in the defaults section, for legacy settings that might be overriding default settings.

The following table demonstrates the critical `multipathd` parameters for ONTAP LUNs and the required values. If a host is connected to LUNs from other vendors and any of these parameters are overridden, they must be corrected by later stanzas in the `multipath.conf` file that apply specifically to ONTAP LUNs. Without this correction, the ONTAP LUNs might not work as expected. You should only override these defaults in consultation with NetApp, the OS vendor, or both, and only when the impact is fully understood.

//ONTAPDOC-2578 9-Dec-2024
//ONTAPDOC-2561 25-Nov-202


[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | infinity
| failback | immediate
| fast_io_fail_tmo | 5
| features | 2 pg_init_retries 50
| flush_on_last_del | yes
| hardware_handler | 0
| no_path_retry | queue
| path_checker | tur
| path_grouping_policy | group_by_prio
| path_selector | service-time 0
| polling_interval | 5
| prio | ontap
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | uniform
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example demonstrates how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because other SAN arrays are still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
默认值{ path_checkerreadsector0 no_path_retry失败}设备{设备{供应商“NetApp”产品"LUN。*" no_path_retry队列path_checkertur }

[listing]
----

NOTE: To configure Oracle Linux 8.8 Red Hat Enterprise Kernel, use the link:hu_rhel_88.html#recommended-settings[recommended settings] for Red Hat Enterprise Linux (RHEL) 8.8.

== KVM settings

You can also use the recommended settings to configure a Kernel-based Virtual Machine (KVM). There are no changes required to configure a KVM as the LUN is mapped to the hypervisor.

== Known issues

There are no known issues for the Oracle Linux 8.8 with ONTAP release.
----