---
sidebar: sidebar 
permalink: hu_rhel_77.html 
keywords: host utilities, red hat, rhel, linux, 7.7, netapp, ontap, netapp 
summary: 在 RHEL 7.7 主机上安装 Linux Host Utilities 以使用 ONTAP LUN 管理 FCP 和 iSCSI 协议操作。 
---
= 为使用ONTAP存储的FCP和iSCSI配置RHEL 7.7
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
"Linux Host Utilities (Linux主机实用程序)"软件为连接到ONTAP存储的Linux主机提供管理和诊断工具。在Red Hat Enterprise Linux (RHEL) 7.7主机上安装Linux Host Utilities时、您可以使用Host Utilities帮助管理使用ONTAP LUN的FCP和iSCSI协议操作。


NOTE: 您不需要手动配置基于内核的虚拟机 (KVM) 设置，因为 ONTAP LUN 会自动映射到虚拟机管理程序。



== 第1步：(可选)启用SAN启动

您可以将主机配置为使用SAN启动来简化部署并提高可扩展性。

.开始之前
使用link:https://mysupport.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的Linux操作系统、主机总线适配器(HBA)、HBA固件、HBA启动BIOS和ONTAP版本是否支持SAN启动。

.步骤
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["创建 SAN 启动 LUN 并将其映射到主机"^](英文)
. 在服务器 BIOS 中为 SAN 启动 LUN 映射到的端口启用 SAN 启动。
+
有关如何启用 HBA BIOS 的信息，请参见供应商专用文档。

. 重新启动主机并验证操作系统是否已启动且正在运行、以验证配置是否成功。




== 第2步：安装Linux Host Utilities

NetApp强烈建议安装Linux主机实用程序、以支持ONTAP LUN管理并协助技术支持收集配置数据。

link:hu_luhu_71.html["安装Linux Host Utilities 7.1"](英文)


NOTE: 安装Linux Host Utilities不会更改Linux主机上的任何主机超时设置。



== 第3步：确认主机的多路径配置

您可以在RHEL 7.7中使用多路径来管理ONTAP LUN。

要确保为主机正确配置了多路径、请验证是否已定义此 `/etc/multipath.conf`文件、以及是否已为ONTAP LUN配置了NetApp建议的设置。

.步骤
. 验证文件是否 `/etc/multipath.conf`存在：
+
[source, cli]
----
ls /etc/multipath.conf
----
+
如果此文件不存在、请创建一个空的零字节文件：

+
[source, cli]
----
touch /etc/multipath.conf
----
. 首次创建文件时 `multipath.conf`、您可能需要启用并启动多路径服务以加载建议的设置：
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. 每次启动主机时、空的 `/etc/multipath.conf`零字节文件都会自动加载NetApp建议的主机多路径参数作为默认设置。您无需更改 `/etc/multipath.conf`主机的文件、因为主机操作系统使用可正确识别和管理ONTAP LUN的多路径参数进行编译。
+
下表显示了Linux操作系统为ONTAP LUN编译的本机多路径参数设置。

+
.显示参数设置
[%collapsible]
====
[cols="2"]
|===
| 参数 | 正在设置 ... 


| detect_prio | 是的。 


| dev_los_TMO | " 无限 " 


| 故障恢复 | 即时 


| fast_io_fail_sMO | 5. 


| features | "3 queue_if_no_path pG_init_retries 50" 


| flush_on_last_del | 是的。 


| 硬件处理程序 | 0 


| no_path_retry | 队列 


| path_checker | "TUR" 


| path_grouping_policy | "Group_by-prio" 


| path_selector | " 服务时间 0" 


| Polling interval | 5. 


| PRIO | ONTAP 


| 产品 | lun.* 


| Retain Attached Hw_handler | 是的。 


| rr_weight | " 统一 " 


| user_friendly_names | 否 


| 供应商 | NetApp 
|===
====
. 验证ONTAP LUN的参数设置和路径状态：
+
[source, cli]
----
multipath -ll
----
+
默认多路径参数支持ASA、 AFF和FAS配置。在这些配置中，单个ONTAP LUN 不应需要超过四条路径。存储故障时，路径超过四条可能会导致问题。

+
以下示例输出显示了ASA、AFF或FAS配置中ONTAP LUN的正确参数设置和路径状态。

+
[role="tabbed-block"]
====
.ASA配置
--
ASA配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.AFF或FAS配置
--
AFF或FAS配置应具有两组优先级较高和较低的路径。优先级较高的主动/优化路径由聚合所在的控制器提供。优先级较低的路径处于活动状态、但未进行优化、因为它们由其他控制器提供服务。只有在优化路径不可用时、才会使用非优化路径。

以下示例显示了具有两个主动/优化路径和两个主动/非优化路径的ONTAP LUN的输出：

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== 第4步：(可选)从多路径中排除设备

如果需要、您可以将不需要的设备的WWID添加到文件的"黑名单"部分、从而将该设备从多路径中排除 `multipath.conf`。

.步骤
. 确定WWID：
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sa"是要添加到黑名单中的本地SCSI磁盘。

+
例如，WWID为 `360030057024d0730239134810c0cb833`。

. 将WWID添加到"黑名单"部分：
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== 第5步：自定义ONTAP LUN的多路径参数

如果您的主机连接到其他供应商的LUN、并且任何多路径参数设置被覆盖、则您需要稍后在文件中添加专门适用于ONTAP LUN的zas来更正这些设置 `multipath.conf`。否则、ONTAP LUN可能无法按预期运行。

请检查 `/etc/multipath.conf`文件，特别是默认值部分中的设置，以了解可能覆盖的设置<<multipath-parameter-settings,多路径参数的默认设置>>。


CAUTION: 您不应覆盖ONTAP LUN的建议参数设置。要获得最佳主机配置性能、需要使用这些设置。有关详细信息、请联系NetApp支持部门、您的操作系统供应商或这两者。

以下示例显示了如何更正被覆盖的默认值。在此示例中、 `multipath.conf`文件为和定义了与 `no_path_retry`ONTAP LUN不兼容的值 `path_checker`、您无法删除这些参数、因为ONTAP存储阵列仍连接到主机。而是通过向专门应用于ONTAP LUN的文件添加设备段来 `multipath.conf`更正和 `no_path_retry`的值 `path_checker`。

.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== 第6步：查看已知问题

使用ONTAP存储版本的RHEL 7.7存在以下已知问题：

[cols="3*"]
|===
| NetApp 错误 ID | 标题 | Description 


| 1440718 | 如果在未执行SCSI重新扫描的情况下取消映射或映射LUN、可能会导致主机上的数据损坏。 | 如果将"disable_changed_WWIDs"多路径配置参数设置为是、则在WWID发生更改时、它将禁用对路径设备的访问。在将路径的WWID还原到多路径设备的WWID之前、多路径将禁用对路径设备的访问。要了解更多信息，请参阅link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["NetApp知识库：Oracle Linux 7上iSCSI LUN上的文件系统损坏"^]。 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1258856["1258856"^] | 在存储故障转移操作期间，使用 Emulex LPe16002 16 Gb FC 的 RHEL7U7 上的远程端口传输到阻止状态 | 在存储故障转移操作期间，使用 LPe16002 16 Gb FC 适配器的 RHEL 7.7 主机上的远程端口可能会传输到 " 已阻止 " 状态。当存储节点恢复到最佳状态时， LIF 也会启动，并且远程端口状态应显示为联机。有时，远程端口状态可能会继续显示为 " 已阻止 " 或 " 不存在 " 。此状态可能会导致多路径层的 LUN 路径出现 " 故障 " 。 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1261474["1261474"^] | 在采用 Emulex LPe32002 32 Gb FC 的 RHEL7U7 上，远程端口传输到 Blocked 状态 | 在存储故障转移操作期间，使用 LPe32002 32 Gb FC 适配器的 RHEL 7.7 主机上的远程端口可能会传输到 " 已阻止 " 状态。当存储节点恢复到最佳状态时， LIF 也会启动，并且远程端口状态应显示为联机。有时，远程端口状态可能会继续显示为 " 已阻止 " 或 " 不存在 " 。此状态可能会导致多路径层的 LUN 路径出现 " 故障 " 。 
|===


== 下一步是什么？

* link:hu-luhu-command-reference.html["了解如何使用Linux Host Utilities工具"] 。
* 了解 ASM 镜像
+
自动存储管理(Automatic Storage Management、ASM)镜像可能需要更改Linux多路径设置、以使ASM能够识别问题并切换到备用故障组。ONTAP上的大多数ASM配置都使用外部冗余、这意味着数据保护由外部阵列提供、ASM不会镜像数据。某些站点使用具有正常冗余的ASM来提供双向镜像、通常在不同站点之间进行镜像。有关详细信息、请参见link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["基于ONTAP的Oracle数据库"^]。


