---
sidebar: sidebar 
permalink: hu_rhel_95.html 
keywords: host utilities, red hat, rhel, linux, 9.5, netapp, ontap, rhel 
summary: 介绍如何将Red Hat Enterprise Linux 9.5与ONTAP结合使用 
---
= 使用运行ONTAP的Red Hat Enterprise Linux 9.5
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用ONTAP SAN主机配置设置将Red Hat Enterprise Linux (RHEL) 9.5配置为目标ONTAP。



== 安装Linux Host Utilities

您可以从下载NetApp Linux主机实用程序软件包，其格式为64-bit.rpm文件link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^]。

NetApp强烈建议安装Linux主机实用程序、但并非强制要求。这些实用程序不会更改 Linux 主机上的任何设置。这些实用程序可改进管理并帮助 NetApp 客户支持收集有关您的配置的信息。

.步骤
. 将64位Linux Host Utilities软件包从下载 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["NetApp 支持站点"^]到主机。
. 安装软件包：
+
`rpm -ivh netapp_linux_unified_host_utilitis-7-1.x86_64`





== 使用SAN工具包

安装NetApp主机实用程序软件包会自动安装该工具包。此套件提供了 `sanlun`实用程序、可帮助您管理LUN和主机总线适配器(HBA)。命令将 `sanlun`返回有关映射到主机的LUN的信息、多路径以及创建启动程序组所需的信息。

在以下示例中， `sanlun lun show` 命令将返回 LUN 信息。

[source, cli]
----
sanlun lun show all
----
.显示示例
[%collapsible]
====
[listing]
----
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
---------------------------------------------------------------------------------------------------------------
vs_sanboot                    /vol/vol_2742/lun              /dev/sdch       host17     FCP        180g    cDOT
vs_coexistence_QLE2742        /vol/fc_vol_2_9/dynamic_lun    /dev/sdcg       host17     FCP        10g     cDOT
vs_coexistence_QLE2742        /vol/fc_vol_2_8/dynamic_lun    /dev/sdcf       host17     FCP        10g     cDOT
vs_coexistence_QLE2742        /vol/fc_vol_2_7/dynamic_lun    /dev/sdce       host17     FCP        10g     cDOT
vs_coexistence_QLE2742        /vol/fc_vol_2_6/dynamic_lun    /dev/sdcd       host17     FCP        10g     cDOT
----
====


== 启用SAN启动

如果您决定使用 SAN 启动，则配置必须支持它。

.开始之前
使用link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的操作系统、HBA、HBA固件、HBA启动BIOS以及ONTAP版本是否受支持。

.步骤
. 将 SAN 启动 LUN 映射到主机。
. 验证是否有多个可用路径。
+

NOTE: 主机操作系统启动并在多个路径上运行后、这些路径将变为可用。

. 在服务器 BIOS 中为 SAN 启动 LUN 映射到的端口启用 SAN 启动。
+
有关如何启用 HBA BIOS 的信息，请参见供应商专用文档。

. 重新启动主机以验证启动是否成功。




== 启用多路径

您可以在RHEL 9.5中使用多路径来管理ONTAP LUN。要使用多路径、 `/etc/multipath.conf`文件必须存在。如果 `/etc/multipath.conf`文件不存在、您可以使用touch命令创建一个空的零字节文件 `/etc/multipath.conf`。您无需更改 `/etc/multipath.conf`文件、因为RHEL 9.5会编译为包含识别和正确管理ONTAP LUN所需的所有设置。


NOTE: 一个LUN不应需要四个以上的路径。超过四个路径可能会在存储故障期间导致路径问题。



=== 所有SAN阵列配置

全SAN阵列(ASA)配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

.示例
以下示例显示了ONTAP LUN的正确输出。

.显示示例
[%collapsible]
====
[listing]
----
multipath -ll
3600a098038314c4a433f577471797958 dm-2 NETAPP,LUN C-Mode
size=180G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 14:0:0:0  sdc  8:32   active ready running
  |- 17:0:0:0  sdas 66:192 active ready running
  |- 14:0:3:0  sdar 66:176 active ready running
  `- 17:0:3:0  sdch 69:80  active ready running
----
====


=== 非ASA配置

对于非ASA配置、应具有两组具有不同优先级的路径。优先级较高的路径为主动/优化路径。这意味着它们由聚合所在的控制器提供服务。优先级较低的路径处于活动状态、但未进行优化、因为它们是从其他控制器提供的。只有在优化路径不可用时、才会使用非优化路径。

.示例
以下示例显示了具有两个主动 / 优化路径和两个主动 / 非优化路径的 ONTAP LUN 的正确输出。

.显示示例
[%collapsible]
====
[listing]
----
multipath -ll
3600a0980383149764b5d567257516273 dm-0 NETAPP,LUN C-Mode
size=150G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:3:0  sdcg 69:64  active ready running
| `- 10:0:0:0  sdb  8:16   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:0  sdc  8:32   active ready running
  `- 16:0:2:0  sdcf 69:48  active ready running
----
====


== 建议设置

对RHEL 9.5操作系统进行编译、可识别ONTAP LUN、并自动为ASA和非ASA配置正确设置所有配置参数。您可以使用以下建议设置进一步优化主机配置的性能。

 `multipath.conf`要启动多路径守护进程、必须存在该文件。如果此文件不存在、您可以使用命令创建一个空的零字节文件 `touch /etc/multipath.conf`。

首次创建 `multipath.conf`文件时、可能需要使用以下命令启用并启动多路径服务：

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
不需要将设备直接添加到文件中 `multipath.conf`、除非您的设备不希望多路径管理、或者您的现有设置会覆盖默认值。您可以通过向文件中添加以下语法来排除不需要的 `multipath.conf`设备、并将<DevId>替换为要排除的设备的WWID字符串：

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
在以下示例中、您将确定设备的WWID并将该设备添加到文件中 `multipath.conf`。

.步骤
. 确定WWID：
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda`是要将其添加到黑名单中的本地SCSI磁盘。

. 添加 `WWID` 到黑名单中 `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


您应始终检查 `/etc/multipath.conf`文件、尤其是在默认部分中、以了解可能会覆盖默认设置的原有设置。

下表显示了 `multipathd`ONTAP LUN的关键参数和所需值。如果主机连接到其他供应商的LUN、并且这些参数中的任何一个被覆盖、则需要在 `multipath.conf`文件中通过稍后的具体适用于ONTAP LUN的说明进行更正。如果不执行此操作， ONTAP LUN 可能无法按预期工作。只有在咨询NetApp和/或操作系统供应商并充分了解影响后、才应覆盖这些默认值。

[cols="2*"]
|===
| 参数 | 正在设置 ... 


| detect_prio | 是的。 


| dev_los_TMO | " 无限 " 


| 故障恢复 | 即时 


| fast_io_fail_sMO | 5. 


| features | "2 pG_INIT_retries 50" 


| flush_on_last_del | 是的。 


| 硬件处理程序 | 0 


| no_path_retry | 队列 


| path_checker | "TUR" 


| path_grouping_policy | "Group_by-prio" 


| path_selector | " 服务时间 0" 


| Polling interval | 5. 


| PRIO | ONTAP 


| 产品 | LUN 


| Retain Attached Hw_handler | 是的。 


| rr_weight | " 统一 " 


| user_friendly_names | 否 


| 供应商 | NetApp 
|===
.示例
以下示例显示了如何更正被覆盖的默认值。在这种情况下、文件将 `multipath.conf`为和 `no_path_retry`定义与ONTAP LUN不兼容的值 `path_checker`。如果其他SAN阵列仍连接到主机、请使用设备标准版专门针对ONTAP LUN更正这些参数。

.显示示例
[%collapsible]
====
[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP"
      product         "LUN"
      no_path_retry    queue
      path_checker     tur
   }
}
----
====


== 配置KVM设置

您无需为基于内核的虚拟机配置设置、因为LUN已映射到虚拟机管理程序。



== 已知问题

对于运行ONTAP版本的RHEL 9.5、FC主机配置没有已知问题。
