---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: 介绍如何在ONTAP中使用Solaris Host Utilities 6.2 
---
= 安装适用于ONTAP存储的Solaris Host Utilities 6.2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris Host Utilities 可帮助您管理连接到 Solaris 主机的ONTAP存储并协助技术支持收集配置数据。

Solaris Host Utilities 支持多种 Solaris 环境和多种传输协议。以下是主要的 Solaris Host Utilities 环境：

* 使用 SPARC 处理器或 x86/64 处理器的系统上的带有 MPxIO 和光纤通道 (FC) 或 iSCSI 协议的本机操作系统。
* 在使用SPARC处理器的系统上使用FC或iSCSI协议的VERITAS动态多路径(DMP)，或者在使用x86/64处理器的系统上使用iSCSI协议的VERITAS动态多路径(DMP)。


Solaris Host Utilities 6.2 支持以下 Solaris 系列：

* Solaris 11.x
* Solaris 10.x


.开始之前
验证您的 iSCSI、FC 或 FCoE 配置是否受支持。您可以使用link:https://imt.netapp.com/matrix/#welcome["互操作性表工具"^]验证您的配置。

.步骤
. 以 root 身份登录到您的主机。
. 从下载包含主机实用程序的压缩文件副本link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["NetApp 支持站点"^]到 Solaris 主机上的目录：
+
[role="tabbed-block"]
====
.SPARC CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.x86/x64 CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. 转到 Solaris 主机上包含下载内容的目录。
. 使用解压缩文件 `gunzip` 命令：
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. 使用提取文件 `tar xvf`命令：
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. 将你从 tar 文件中提取的软件包添加到你的主机
+
[source, cli]
----
pkgadd
----
+
这些软件包将添加到 ` /opt/NTAP/SANToolkit/bin` 目录中。

+
以下示例将使用 `pkgadd`命令安装Solaris安装包：

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. 使用以下命令之一确认工具包已成功安装：
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.显示示例输出
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. 为您的 MPxIO 或 Veritas DMP 环境配置主机参数：
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. 验证安装。
+
[source, cli]
----
sanlun version
----




== 下一步是什么？

link:hu-solaris-san-toolkit.html["了解 SAN 工具包"] 。
