---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows Host Utilities包括一个安装程序、用于设置所需的Windows注册表和HBA参数、以便Windows主机正确处理ONTAP和E系列平台的存储系统行为。 
---
= 安装Windows Host Utilities 7.2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用Windows主机实用程序可以将Windows主机计算机连接到NetApp存储系统。

Windows Host Utilities支持以下Windows版本：

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Windows主机实用程序包括一个安装程序、用于设置所需的Windows注册表和主机总线适配器(HBA)参数、以便Windows主机可以正确处理ONTAP和E系列平台的存储系统行为。

安装Host Utilities软件时、安装程序会设置所需的Windows注册表和HBA参数。

Windows 主机计算机上安装了以下程序和文件。默认目录为 `C ： \Program Files\NetApp\Windows Host Utilities` 。

|===
| 计划 | 目的 


| `` m é exhba.reg | 故障排除程序；只有在技术支持人员要求时，才运行此程序。 


| ` \NetAppQCL1\fcconfig.exe` | 由安装程序用于设置HBA参数。 


| ` \NetAppQCL1\fcconfig.ini` | 由安装程序用于设置HBA参数。 


| ` \NetAppQCLI\* 。 *` | 由安装程序用于设置QLogic FC HBA参数。 


| `sA_version.exe` | 显示Host Utilities和FC HBA的版本。 
|===
Host Utilities支持不同的Windows主机配置、协议和多路径选项。有关详细信息，请参见 https://mysupport.netapp.com/matrix/["互操作性表工具"^]。



== 验证主机和存储系统配置

在安装适用于的Windows Host Utilities之前，请验证您的主机和存储系统配置是否受支持<<supported-windows-versions-72,支持的Windows版本>>。

.步骤
. 在中检查支持的配置 http://mysupport.netapp.com/matrix["互操作性表工具"^]。
. 在中检查相应主机所需的修补程序 link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主机Windows文档"]。
+

NOTE: 本link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["将Windows Server 2022与ONTAP结合使用"]文档提供了有关适用于Windows Server 2022的说明link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["安装Windows修补程序"]。请参见主机配置类别中的Windows文档、以查找早期版本的Windows服务器的相关修补程序信息。

. 添加iSCSI、FCP或NVMe-oF许可证并启动目标服务。
+

NOTE: 在使用SANtricity存储管理器的E系列存储系统上、FC和iSCSI协议不需要许可证。

. 验证布线。
+
请参见 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 配置参考"^] 适用于您的ONTAP或版本的文档 https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["E系列硬件布线"^] 有关布线和配置的详细信息。





== 配置 FC HBA 和交换机

安装并配置一个或多个受支持的FC主机总线适配器(HBA)、以便与存储系统建立FC连接。

Windows Host Utilities安装程序可设置所需的FC HBA设置。


CAUTION: 请勿手动更改HBA设置。

.步骤
. 按照HBA供应商提供的说明安装一个或多个受支持的FC HBA。
. 获取受支持的 HBA 驱动程序和管理实用程序，并按照 HBA 供应商提供的说明进行安装。
. 将HBA连接到FC交换机或直接连接到存储系统。
. 根据FC交换机文档在FC交换机上创建分区。
. 对于ONTAP 、请按WWPN对交换机进行分区。请务必使用逻辑接口(LIF)的WWPN、而不是存储控制器上物理端口的WWPN。请参见 https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 配置参考"^] 有关详细信息，请参见相关文档。




== 安装 Host Utilities

安装程序将安装 Host Utilities 软件包并设置 Windows 注册表和 HBA 设置。

您必须指定在安装Windows Host Utilities软件包时是否包括多路径支持。安装程序将提示您输入以下选项。您也可以从 Windows 命令提示符处运行静默（无人参与）安装。

.多路径支持
* 选择 `MPIO` 从Windows主机或虚拟机到存储系统的路径不止一个。
* 选择 `no MPIO` 仅当您使用存储系统的单个路径时。


Microsoft多路径I/O (MPIO)选项不适用于Windows XP和Windows Vista系统；这些子操作系统不支持多路径I/O。对于 Hyper-V 子系统，如果选择多路径支持，则原始（直通）磁盘不会显示在子操作系统中。您可以使用原始磁盘，也可以使用 MPIO ，但不能在子操作系统中同时使用这两者。

您可以以交互方式安装Host Utilities、也可以使用命令行安装Host Utilities。新的 Host Utilities 安装包必须位于 Windows 主机可访问的路径中。按照说明以交互方式或从Windows命令行安装Host Utilities。

[role="tabbed-block"]
====
.以交互方式安装
--
要以交互方式安装 Host Utilities 软件包，您必须运行 Host Utilities 安装程序并按照提示进行操作。

.步骤
. 从下载可执行文件 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["NetApp 支持站点"^]。
. 更改为下载可执行文件的目录。
. 运行 `netapp_windows_host_utilities_7.2_x64` 归档并按照屏幕上的说明进行操作。
. 出现提示时重新启动 Windows 主机。


--
.从命令行安装
--
您可以在Windows命令提示符处输入相应的命令、以静默(无人值守)方式安装Host Utilities。安装完成后，系统将自动重新启动。

.步骤
. 在Windows命令提示符处输入以下命令：
+
`msiexec /i installer.msi /quiet multipath= ｛ 0` 1 ｝ [INSTALLDIR=inst_path]

+
** `installer` 是的名称 `.msi` 适用于CPU架构的文件。
** 多路径用于指定是否安装 MPIO 支持。允许的值为"0"表示否、"1"表示是。
** `inst_path` 是安装 Host Utilities 文件的路径。默认路径为 `C ： \Program Files\NetApp\Windows Host Utilities\` 。





NOTE: 要查看用于日志记录和其他功能的标准Microsoft安装程序(MSI)选项、请输入 `msiexec /help` 在Windows命令提示符处。例如、 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 命令可显示日志记录信息。

--
====