---
sidebar: sidebar 
permalink: hu_wuhu_71_rn.html 
keywords: host utilities, linux, 7.1, 7.2, netapp, ontap, release, notes 
summary: 《Windows Unified Host Utilities发行说明》 
---
= 《Windows Unified Host Utilities发行说明》
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
本发行说明文档包含Windows Unified Host Utilities 7.2和7.1版的最新信息、包括有关新功能、增强功能和已知问题的更新。当有关使用Windows Host Utilities的新信息可用时、本文档将进行更新。



== 关于Windows Unified Host Utilities

通过Windows Unified Host Utilities、您可以将Windows主机计算机连接到NetApp存储系统。Windows Unified Host Utilities包含一个安装程序、用于设置所需的Windows注册表和HBA值。

Windows Unified Host Utilities仍支持以下版本的Windows：

* Windows 2012
* Windows 2012R2
* Windows 2016
* Windows 2019
* Windows 2022



NOTE: NetApp对Host Utilities软件两个版本之间的其他组件进行了资格认定。有关系统要求的最新信息、请参见 link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp 互操作性表工具"^]。



== 功能

* Windows Unified Host Utilities 7.2支持NVMe/FC驱动程序参数设置、并可修复新供应商卡的错误。
* Windows Unified Host Utilities 7.1支持E系列存储系统、支持ONTAP 9及更高版本、并增强了iSCSI超时功能、可加快故障转移速度。




== 重要注意事项

在部署最新版本的Windows Host Utilities之前、您必须阅读可用信息、以帮助您确定并解决可能影响系统运行的问题。

有关单个错误的详细信息以及探索其他与错误相关的工具、请参见 link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bug Online"^]。



=== 安装所需的修补程序

要确保成功安装或升级Windows Unified Host Utilities、您需要安装特定的Windows修补程序。某些修补程序是Windows更新的一个组件。

请参见 link:hu_wuhu_72.html["Windows Host Utilities文档"] 以满足您的特定配置修补程序要求。



== 已知问题

在7.1版中、我们发现了一些意外的、可能不受欢迎的行为、以及在某些情况下避免这些行为的解决方法。

[cols="30, 30, 20"]
|===
| 标题 | Description | 临时解决策 


| 运行 `linux_gos_timeout-install.sh` 运行Red Hat Enterprise Linux或SUSE Linux Enterprise Server的Hyper-V子系统不再需要脚本 | 您不再需要运行 `linux_gos_timeout-install.sh` 用于更改Red Hat Enterprise Linux 5、Red Hat Enterprise Linux 6或SUSE Linux Enterprise Server 11 Hyper-V子系统上的磁盘超时的脚本、因为正在使用默认超时设置。。 `linux_gos_timeout-install.sh` 先前版本的Host Utilities中包含的脚本不再包含在Windows Unified Host Utilities中。Windows Unified Host Utilities 7.1使用默认磁盘超时设置。 | 不适用 


| 使用IPv4和IPv6混合重新启动后、iSCSI会话不会重新连接 | 在多路径I/O (MPIO)配置或同时具有IPv4和IPv6端点的多个会话连接(MCS)配置中、某些iSCSI会话可能无法在重新启动Windows主机后重新连接。 | 要在重新启动后验证所有iSCSI路径是否均返回、请使用所有IPv4端点或所有IPv6。请勿混合使用IPv4和IPv6。 


| iSCSI软件启动不支持MCS | 如果将iSCSI软件启动与每个会话的iSCSI多个连接(MCS)结合使用、则无法保护iSCSI启动前导连接。这可能会导致与启动LUN断开连接、从而导致主机崩溃。 | 对于iSCSI软件启动的主机、Microsoft不支持MCS。使用MPIO作为高可用性解决方案。请注意、不支持混合使用MPIO和MCS。 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bug Online"^] 提供有关大多数已知问题的完整信息、包括可能的建议解决方法。



== 关于SAN主机配置文档

有关SAN主机实用程序的文档、请参见 link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SAN主机配置文档"]。ONTAP SAN主机配置文档是累积的、涵盖所有当前的SAN主机版本。各个版本之间的任何功能差异都会在上下文中注明。



== 从何处查找产品文档和其他信息

您可以访问所有NetApp产品的文档、并在NetApp公司站点的产品文档页面上查找其他产品信息资源、例如技术报告和白皮书。

.相关信息
*配置和管理ONTAP 存储系统*

* 。 link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html["《ONTAP 软件设置指南》"^] 适用于您的ONTAP 版本
* 。 link:https://docs.netapp.com/us-en/ontap/san-management/index.html["《ONTAP SAN管理指南》"^] 适用于您的ONTAP 版本
* 。 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["《 ONTAP 发行说明》"^] 适用于您的ONTAP 版本


*配置和管理E系列存储系统*

* 适用于您的协议的《SANtricity 存储管理器Windows配置和配置快速指南》
* 适用于您的操作系统、协议和SANtricity 版本的《SANtricity 存储管理器配置和配置快速指南》。
* 适用于您的SANtricity 版本的《SANtricity 存储管理器软件安装参考》。
* 适用于您的SANtricity 版本的SANtricity 存储管理器多路径驱动程序指南。
* 适用于您的SANtricity 版本的《SANtricity 存储管理器发行说明》。


请参见 link:https://docs.netapp.com/us-en/e-series-family/["E 系列文档"^] 查找SANtricity 相关文档。
