---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilities包括一个安装程序、用于设置所需的Windows注册表和HBA参数、以便Windows主机正确处理ONTAP和E系列平台的存储系统行为。 
---
= 升级适用于ONTAP存储的 Windows Host Utilities
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以按照安装说明以交互方式或使用 Windows 命令行来升级ONTAP存储配置中的 Windows Host Utilities 软件。您需要将新的 Windows Host Utilities 安装软件安装在 Windows 主机可访问的路径上。

[role="tabbed-block"]
====
.以交互方式升级
--
通过运行 Host Utilities 安装程序并按照提示以交互方式升级 Windows Host Utilities 软件。

.步骤
. 更改为下载可执行文件的目录。
. 运行可执行文件并按照屏幕上的说明进行操作。
. 出现提示时重新启动 Windows 主机。
. 重新启动完成后、请检查主机实用程序版本：
+
.. 打开 * 控制面板 * 。
.. 转至 * 程序和功能 * 并检查主机实用程序版本。




--
.非交互升级
--
使用 Windows 命令行执行非交互式 Windows Host Utilities 软件升级。

.步骤
. 在Windows命令提示符处输入以下命令：
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` 是的名称 `.msi` 适用于CPU架构的文件。
** 多路径用于指定是否安装Microsoft多路径I/O (MPIO)支持。允许的值为"0"表示否、"1"表示是。
** `inst_path` 是安装 Host Utilities 文件的路径。默认路径为 `C ： \Program Files\NetApp\Windows Host Utilities\` 。





NOTE: 要查看用于日志记录和其他功能的标准Microsoft安装程序(MSI)选项、请输入 `msiexec /help` 在Windows命令提示符处。例如、 `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` 命令可显示日志记录信息。

安装完成后，系统将自动重新启动。

--
====