---
sidebar: sidebar 
permalink: nvme-windows-2012r2.html 
keywords: nvme, windows, enterprise 
summary: '您可以在运行Windows Server 2012 R2的主机上配置基于光纤通道的NVMe (NVMe/FC)、以便使用ONTAP LUN进行操作。' 
---
= 为ONTAP配置采用NVMe/FC的Windows Server 2012 R2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在运行Windows Server 2012 R2的主机上配置基于光纤通道的NVMe (NVMe/FC)、以便使用ONTAP LUN进行操作。

.关于此任务
您可以对适用于Windows 2012 R2的NVMe/FC主机配置使用以下支持。在开始配置过程之前、您还应查看已知限制。


NOTE: 您可以使用此过程中提供的配置设置来配置连接到和link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["适用于 ONTAP 的 Amazon FSX"^]的云客户端link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]。

* 提供支持：
+
从ONTAP 9.7开始、Windows Server 2012 R2支持NVMe/FC。

+
有关支持的FC适配器和控制器的列表，请参见link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]。有关支持的配置和版本的最新列表，请参见link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]。

* 已知限制：
+
NVMe/FC不支持Windows故障转移集群、因为ONTAP目前不支持使用NVMe/FC进行永久性预留。

+

NOTE: Broadcom为Windows NVMe/FC提供了一个外部驱动程序、该驱动程序是转换式SCSI⇄NVMe驱动程序、而不是真正的NVMe/FC驱动程序。翻译开销不一定会影响性能、但它会使NVMe/FC的性能优势无效。因此、与Linux等其他操作系统不同、Windows服务器上的NVMe/FC和FCP性能相同、在这些操作系统中、NVMe/FC性能明显优于FCP。





== 启用 NVMe/FC

在Windows启动程序主机上启用FC/NVMe。

.步骤
. 在Windows主机上安装Emulex HBA Manager实用程序。
. 在每个 HBA 启动程序端口上，设置以下 HBA 驱动程序参数：
+
** EnableNVMe = 1
** NVMEMode = 0


. 重新启动主机。




== 配置Broadcom FC适配器

Broadcom启动程序可通过相同的32 G FC适配器端口同时提供NVMe/FC和FCP流量。对于FCP和FC/NVMe、应使用Microsft设备专用模块(DSM)作为Microsoft多路径I/O (MPIO)选项。

 `+hostnqn+`在Windows环境中、与采用FC/NVMe的Broadcom适配器的每个主机总线适配器(HBA)端口关联。的 `+hostnqn+`格式如下所示：

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== 为NVMe设备启用MPIO

要在Windows主机上完成NVMe配置、您需要为NVMe设备启用MPIO。

.步骤
. 安装 link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Windows Host Utility Kit 7.1"] 设置FC和NVMe通用的驱动程序参数。
. 打开 MPIO 属性。
. 从 * 发现多路径 * 选项卡中，添加为 NVMe 列出的设备 ID 。
+
MPIO 可以识别 NVMe 设备，这些设备可在磁盘管理下查看。

. 打开 * 磁盘管理 * 并转到 * 磁盘属性 * 。
. 从*MPIO*选项卡中，选择*Details*。
. 设置以下Microsoft DSM设置：
+
** PathVerifiedPeriod ： *
** PathVerifyEnabled ： * 启用 *
** RetransyCount ： *
** RetransyInterval ： *
** PDORemovedPeriod ： * 130 *


. 选择 MPIO 策略 * 使用子集执行轮循 * 。
. 更改注册表值：
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. 重新启动主机。




== 验证 NVMe/FC

确认已发现NVMe子系统、并且ONTAP命名卷对于NVMe-oF配置正确无误。

.步骤
. 验证“Port Type (端口类型)”是否为 `+FC+NVMe+`：
+
`listhba`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. 验证是否已发现NVMe/FC子系统：
+
** `+nvme-list+`
+
.显示示例
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.显示示例
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. 验证是否已创建这些名称空间：
+
`+nvme-list-ns+`

+
.显示示例
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

