---
sidebar: sidebar 
permalink: nvme_rhel_81.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: 介绍如何使用 ONTAP 为 RHEL 8.1 配置 NVMe/FC 
---
= 适用于采用ONTAP的RHEL 8.1的NVMe/FC主机配置
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
对于Red Hat Enterprise Linux (RHEL) 8.1、ONTAP 9.6或更高版本支持NVMe/FC。RHEL 8.1主机可以通过相同的FC启动程序适配器端口同时运行NVMe和SCSI流量。请参见 link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] 有关支持的 FC 适配器和控制器的列表。

请参见 link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具"^] 了解最新的受支持配置列表。



== 已知限制

* 中不提供本机NVMe/FC自动连接脚本 `nvme-cli` 软件包。您可以使用主机总线适配器(HBA)供应商提供的外部自动连接脚本。
* 默认情况下、NVMe多路径处于禁用状态。因此，您需要手动启用它。
* 默认情况下，不会启用轮循负载平衡。您可以通过写入来启用此功能 `udev` 规则。
* 目前不支持使用NVMe-oF协议启动SAN。




== 启用 NVMe/FC

您可以使用以下操作步骤启用NVMe/FC。

.步骤
. 在服务器上安装 Red Hat Enterprise Linux 8.1 。
. 安装完成后、验证是否正在运行指定的RHEL内核：
+
[listing]
----
# uname -r
4.18.0-147.el8.x86_64
----
+
请参见 link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具"^] 有关最新的受支持版本列表。

. 安装 `nvme-cli-1.8.1-3.el8` 软件包：
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.8.1-3.el8.x86_64
----
. 启用内核 NVMe 多路径。
+
[listing]
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-147.el8.x86_64
----
. 将以下字符串作为单独的UDEv规则添加到 `/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules`。这样可以为NVMe多路径启用循环负载平衡：
+
[listing]
----
# Enable round-robin for NetApp ONTAP
ACTION==”add”, SUBSYSTEM==”nvme-subsystem”, ATTR{model}==”NetApp ONTAP Controller”, ATTR{iopolicy}=”round-robin
----
. 在RHEL 8.1主机上、检查中的主机NQN字符串 `/etc/nvme/hostnqn` 并验证它是否与ONTAP阵列上对应子系统的主机NQN字符串匹配：
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[listing]
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
rhel_141_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+

NOTE: 如果主机NQN字符串不匹配、请使用 `vserver modify` 命令更新相应ONTAP阵列子系统上的主机NQN字符串、以便与中的主机NQN字符串匹配 `/etc/nvme/hostnqn` 在主机上。

. 重新启动主机。




== 为 NVMe/FC 配置 Broadcom FC 适配器

您可以使用以下操作步骤配置Broadcom FC适配器。

.步骤
. 验证您使用的是受支持的适配器。请参见 link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具"^] 有关支持的适配器的最新列表。
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 复制并安装Broadcom lpfc发件箱驱动程序和自动连接脚本：
+
[listing]
----
# tar -xvzf elx-lpfc-dd-rhel8-12.4.243.20-ds-1.tar.gz
# cd elx-lpfc-dd-rhel8-12.4.2453.20-ds-1
# ./elx_lpfc_install-sh -i -n
----
+

NOTE: 与操作系统捆绑的本机驱动程序称为内置驱动程序。如果下载发件箱驱动程序(操作系统版本未附带的驱动程序)、则下载中会包含一个自动连接脚本、该脚本应在驱动程序安装过程中安装。

. 重新启动主机。
. 验证是否正在使用建议的Broadcom lpfc固件、发件驱动程序和自动连接软件包版本：
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.4.243.20, sil-4.2.c
12.4.243.20, sil-4.2.c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.4.243.20
----
+
[listing]
----
# rpm -qa | grep nvmefc
nvmefc-connect-12.6.61.0-1.noarch
----
. 请验证 `lpfc_enable_fc4_type` 设置为3：
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. 验证启动程序端口是否已启动且正在运行。
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
. 验证NVMe/FC启动程序端口是否已启用且正在运行、并且您可以看到目标生命周期：
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2977 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
…
----




== 为 Broadcom NVMe/FC 启用 1 MB I/O 大小

ONTAP会在"识别 控制器"数据中报告MDTS (MAX Data传输大小)为8。这意味着最大I/O请求大小最多可以为1 MB。要向Broadcom NVMe/FC主机发出大小为1 MB的I/O请求、必须将 `lpfc` `lpfc_sg_seg_cnt`参数的值从默认值64增加到256。

.步骤
. 将 `lpfc_sg_seg_cnt`参数设置为256：
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. 运行 `dracut -f`命令并重新启动主机：
. 验证是否 `lpfc_sg_seg_cnt`为256：
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----



NOTE: 这不适用于逻辑NVMe/FC主机。



== 验证 NVMe/FC

您可以使用以下操作步骤 来验证NVMe/FC。

.步骤
. 验证以下 NVMe/FC 设置。
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. 验证是否已创建命名空间。
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. 验证 ANA 路径的状态。
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. 验证适用于 ONTAP 设备的 NetApp 插件。
+
[listing]
----

# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----

