---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: 如何使用ONTAP为AIX配置NVMe/FC主机 
---
= 适用于采用ONTAP的AIX的NVMe/FC主机配置
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在使用ONTAP存储作为目标的IBM AIX和VIOS/PowerVM主机上启用基于光纤通道的NVMe (NVMe/FC)。有关支持的配置的其他详细信息、请参见 link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具"^]。

以下支持适用于使用ONTAP的AIX主机的NVMe/FC主机配置：

* 从ONTAP 9.13.1开始、为IBM AIX 7.2 TL5 SP6、AIX 7.3 TL1 SP2和VIOS 3.1.4.21版本增加了NVMe/FC支持、并支持物理堆栈和虚拟堆栈的SAN启动。有关设置SAN启动支持的详细信息、请参见IBM文档。
* POWER9和Power10 IBM服务器支持NVMe/FC。
* NVMe设备不需要单独的PCM (路径控制模块)、例如Host Utilities for AIX SCSI Multipath I/O (MPIO)支持。
* VIOS 3.1.4.21引入了NetApp虚拟化支持(VIOS/PowerVM)。这在使用Power10 IBM服务器的NPIV (N_portID虚拟化)存储虚拟化模式中仅受支持。


.您需要的内容
* 确认您已安装32 Gb FC Emulex适配器(EN1A、EN1B、EN1L)或64 Gb FC适配器(EN1n、EN1P)、且适配器固件为12.4.257.半 及更高版本。
* 如果您具有MetroCluster配置、NetApp建议更改支持MetroCluster计划外切换事件的AIX NVMe/FC默认APD (所有路径关闭)时间、以避免AIX操作系统强制执行较短的I/O超时。有关追加信息以及建议的默认设置更改、请参阅NetApp错误在线- link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249."^]。
* 默认情况下、AIX主机操作系统的非对称命名空间访问过渡超时(AATT)值为30秒。IBM提供了一个临时修复(IFIX)、该修复会将ANATT值上限设置为60秒；您需要从IBM网站安装IFIX、以确保所有ONTAP工作流均无中断。
+

NOTE: 要获得NVMe/FC AIX支持、必须在AIX OS的GA版本上安装IFIX。VIOS/PowerVM操作系统不需要执行此操作。

+
IFIX的详细信息如下：

+
** 对于AIX版本72-TL5-SP6-2320、安装 `IJ46710s6a.230509.epkg.Z` 软件包。
** 对于AIX Level 73-TL1-SP2-2320、安装 `IJ46711s2a.230509.epkg.Z` 软件包。
+
有关管理ifixes的详细信息、请参见 link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["管理AIX上的临时修复程序"^]。

+

NOTE: 您需要在以前没有与相关的已安装ifixes的AIX版本上安装ifixes `devices.pciex.pciexclass.010802.rte` 在系统上。如果存在这些ifixes、它们将与新安装冲突。

+
下表显示了分配给AIX LPAR (AIX逻辑分区)或物理堆栈的HBA：

+
[cols="10,10,10,10,10"]
|===
| 主机操作系统 | Power Arch | 电源固件版本 | 模式 | 注释 


.2+| AIX 7.2 TL5 SP6 | POWER9 | FW 950或更高版本 | 物理堆栈 | 通过TS012877410提供IFIX。 


| Power10 | FW 1010或更高版本 | 物理堆栈 | 支持SAN启动。通过TS012877410提供IFIX。 


.2+| AIX 7.3 TL1 SP2 | POWER9 | FW 950或更高版本 | 物理堆栈 | 通过TS012877410提供IFIX。 


| Power10 | FW 1010或更高版本 | 物理和虚拟堆栈 | 通过TS012877410提供IFIX。 
|===
+
下表显示了在虚拟化模式下分配给VIOS且支持NPIV的HBA：

+
[cols="10,10,10,10,10"]
|===
| 主机操作系统 | Power Arch | 电源固件版本 | 模式 | 注释 


| VIOS/PowerVM 3.1.4.21 | Power10 | FW 1010或更高版本 | 虚拟堆栈 | 从适用于VIOC的AIX 7.3 TL1 SP2开始提供支持 
|===






== 已知限制

适用于采用ONTAP的AIX的NVMe/FC主机配置具有以下已知限制：

* AIX主机上的QLogic/Marvel 32G FC HBA不支持NVMe/FC。
* 使用POWER9 IBM服务器的NVMe/FC设备不支持SAN启动。




== 多路径

默认情况下、在安装AIX操作系统时会提供用于NVMe多路径的IBM MPIO (多路径I/O)。

您可以使用验证是否已为AIX主机启用NVMe多路径 `lsmpio` 命令：

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*示例输出*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== 配置 NVMe/FC

您可以使用以下操作步骤为Broadcom/Emulex适配器配置NVMe/FC。

.步骤
. 验证您使用的是受支持的适配器。有关支持的适配器的最新列表，请参见 link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具"^]。
. 默认情况下、在物理FC中启用了NVMe/FC协议支持；但是、在虚拟I/O服务器(VIOS)上的虚拟光纤通道(VFC)中禁用了NVMe/FC协议支持。
+
检索虚拟适配器列表：

+
[listing]
----
$ lsmap -all -npiv
----
+
*示例输出*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
. 通过运行在适配器上启用对NVMe/FC协议的支持 `ioscli vfcctrl` VIOS上的命令：
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*示例输出*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. 验证是否已在适配器上启用支持：
+
[listing]
----
# lsattr -El vfchost0
----
+
*示例输出*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. 为所有当前适配器或选定适配器启用NVMe/FC协议：
+
.. 为所有适配器启用NVMe/FC协议：
+
... 更改 `dflt_enabl_nvme` 的属性值 `viosnpiv0` 伪设备 `yes`。
... 设置 `enable_nvme` 属性值为 `yes` 适用于所有VFC主机设备。
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*示例输出*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. 通过更改为选定适配器启用NVMe/FC协议 `enable_nvme` VFC主机设备属性的值 `yes`。


. 请验证 `FC-NVMe Protocol Device` 已在服务器上创建：
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
*示例输出*

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. 记录服务器中的主机NQN：
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*示例输出*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*示例输出*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
. 检查主机NQN并验证它是否与ONTAP阵列上对应子系统的主机NQN字符串匹配：
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*示例输出*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. 验证启动程序端口是否已启动且正在运行、并且您可以看到目标生命周期。




== 验证 NVMe/FC

您需要验证ONTAP名称卷是否正确反映在主机上。为此、请运行以下命令：

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*示例输出*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
您可以检查多路径状态：

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*示例输出*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== 已知问题

适用于采用ONTAP的AIX的NVMe/FC主机配置存在以下已知问题：

[cols="10,30,30"]
|===
| BURT ID (BURT ID) | 标题 | Description 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249."^] | 要修改的AIX NVMe/FC默认APD时间、以支持MCC计划外切换事件 | 默认情况下、AIX操作系统会对NVMe/FC使用全路径关闭(APD)超时值20秒。  但是、ONTAP MetroCluster自动计划外切换(Automatic Undurrated SwitchOver、AUSO)和Tieb破碎 机启动的切换工作流所需时间可能比APD超时窗口要长一些、从而导致I/O错误。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | AIX NVMe/FC将ANATT上限设置为60秒、而不是ONTAP公布的120秒 | ONTAP在控制器标识中显示ANA (非对称命名空间访问)过渡超时为120秒。目前、借助IFIX、AIX会从控制器标识读取ANA过渡超时、但如果超过此限制、则会将其有效地固定到60秒。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | 在AATT到期后、AIX NVMe/FC会命中EIO | 对于任何存储故障转移(Storage Failover、SFO)事件、如果ANA (非对称命名空间访问)过渡超过给定路径上的ANA过渡超时上限、则AIX NVMe/FC主机将失败、并显示I/O错误、尽管命名空间具有备用的运行状况良好的路径。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC等待半/全AATT过期、然后在ANA AEN之后恢复I/O | IBM AIX NVMe/FC不支持ONTAP发布的某些异步通知(Aschron也 会通知、AEN)。这种次优ANA处理方式会导致SFB操作期间性能欠佳。 
|===


== 故障排除

在对任何NVMe/FC故障进行故障排除之前、请验证您运行的配置是否符合互操作性表工具(IMT)规范。如果您仍然遇到问题、请联系 link:mysupport.netapp.com["NetApp 支持"^] 以便进一步鉴别。
