---
sidebar: sidebar 
permalink: nvme-aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: 如何使用ONTAP为AIX配置NVMe/FC主机 
---
= 使用 NVMe-oF 为ONTAP存储配置 AIX
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
IBM AIX 和虚拟 I/O 服务器 (VIOS)/PowerVM 主机支持具有非对称命名空间访问 (ANA) 的 NVMe/FC 协议。  ANA 相当于 iSCSI 和 FCP 环境中的非对称逻辑单元访问 (ALUA) 多路径。

有关受支持配置的更多详细信息，请参阅link:https://mysupport.netapp.com/matrix/["互操作性表工具(IMT)"^]。

.关于此任务
您可以将以下支持和功能与 AIX 主机的 NVMe-oF 主机配置一起使用。在开始配置过程之前，您还应该查看已知的限制。

* 提供支持：
+
** 从ONTAP 9.13.1 开始，IBM AIX 7.2 TL5 SP6、AIX 7.3 TL1 SP2 和 VIOS 3.1.4.21 添加了 NVMe/FC 支持，并为物理和虚拟堆栈提供了 SAN 启动支持。有关设置 SAN 启动支持的更多信息，请参阅 IBM 文档。
** POWER9和Power10 IBM服务器支持NVMe/FC。
** NVMe 设备不需要单独的 PCM（路径控制模块），例如用于 AIX SCSI 多路径 I/O（MPIO）支持的主机实用程序。
** VIOS 3.1.4.21引入了NetApp虚拟化支持(VIOS/PowerVM)。这在使用Power10 IBM服务器的NPIV (N_portID虚拟化)存储虚拟化模式中仅受支持。


* 已知限制：
+
** AIX 主机上的 Qlogic/Marvel 32G FC HBA 不支持 NVMe/FC。
** 使用 Power9 IBM 服务器的 NVMe/FC 设备不支持 SAN 启动。




.开始之前
* 确认您已安装32 Gb FC Emulex适配器(EN1A、EN1B、EN1L)或64 Gb FC适配器(EN1n、EN1P)、且适配器固件为12.4.257.半 及更高版本。
* 如果您具有MetroCluster配置、NetApp建议更改支持MetroCluster计划外切换事件的AIX NVMe/FC默认APD (所有路径关闭)时间、以避免AIX操作系统强制执行较短的I/O超时。有关追加信息以及建议的默认设置更改、请参阅NetApp错误在线- link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249."^]。
* 根据您的 AIX 版本，AIX 主机操作系统的非对称命名空间访问转换超时 (ANATT) 默认为 30 秒或 60 秒。如果您的主机的 ANATT 默认值为 30 秒，则需要从 IBM 网站安装 IBM Interim Fix (ifix)，将 ANATT 设置为 60 秒，以确保所有ONTAP工作流程都不会中断。
+
[NOTE]
====
要获得 NVMe/FC AIX 支持，您必须在 GA 版本的 AIX OS 上安装 ifix。  VIOS/PowerVM OS 不需要 ifix。

您需要在之前没有安装过相关 ifix 的 AIX 版本上安装 ifix `devices.pciex.pciexclass.010802.rte`在系统上。以前安装的 iFIX 可能会与新安装冲突。

====
+
[role="tabbed-block"]
====
.将 ANATT 设置为 60 秒
--
AIX 级别 72-TL5-SP6-2320 和 AIX 级别 73-TL1-SP2-2320 版本的默认 ANATT 为 30 秒。 IBM 提供了一个 iFIX，将 ANATT 设置为 60 秒。您可以通过 IBM 案例 ID TS018079082 获得 ifix，并且您可以为以下 AIX 版本安装它：

** 对于AIX版本72-TL5-SP6-2320、安装 `IJ46710s6a.230509.epkg.Z` 软件包。
** 对于AIX Level 73-TL1-SP2-2320、安装 `IJ46711s2a.230509.epkg.Z` 软件包。


--
.默认 ANATT 为 60 秒
--
对于以下 AIX 版本，默认 ANATT 为 60 秒：

** AIX 级别 73-TL2-SP3-2446
** AIX 级别 73-TL2-SP2-2420
** AIX 级别 72-TL5-SP8-2420


--
.（可选）将 ANATT 设置为 120 秒
--
IBM 提供了一个 iFIX，将 ANATT 设置为 120 秒。将 ANATT 设置为 120 秒时，它会增强ONTAP存储故障转移事件期间的性能。您可以通过 IBM 案例 ID TS012877410 获得 ifix，并且您可以为以下 AIX 版本安装它：

** 对于 AIX 级别 73-TL3-SP0-2446，安装 `IJ53487s0a.250130.epkg.Z`包裹。
** 对于 AIX 级别 72-TL5-SP9-2446，安装 `IJ53445s9a.250130.epkg.Z`包裹。


--
====
+
[NOTE]
====
支持 NVMe/FC 的 Power9 服务器的最低服务器固件版本为 FW 950。

支持 NVMe/FC 的 Power10 服务器的最低服务器固件版本为 FW 1010。

====
+
有关管理ifixes的详细信息、请参见 link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["管理AIX上的临时修复程序"^]。





== 步骤 1：确认主机的多路径配置

安装 AIX 操作系统时，默认启用用于 NVMe 多路径的 IBM MPIO。

.步骤
. 验证 NVMe 多路径是否已启用：
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.显示示例
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== 步骤 2：配置 NVMe/FC

您需要为 VIOS 上的 Broadcom/Emulex 适配器配置 NVMe/FC，因为 VIOS 上的虚拟光纤通道 (vFC) 中禁用了 NVMe/FC 协议支持。物理 FC 中默认启用 NVMe/FC 协议支持。

.步骤
. link:https://mysupport.netapp.com/matrix/["验证您正在使用受支持的适配器"^] 。
. 检索虚拟适配器列表：
+
[source, cli]
----
lsmap -all -npiv
----
+
.显示示例
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. 通过运行在适配器上启用对NVMe/FC协议的支持 `ioscli vfcctrl` VIOS上的命令：
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.示例输出
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. 验证是否已在适配器上启用支持：
+
[source, cli]
----
lsattr -El vfchost0
----
+
.显示示例
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. 为所有适配器启用NVMe/FC协议：
+
.. 更改 `dflt_enabl_nvme` 的属性值 `viosnpiv0` 伪设备 `yes`。
.. 设置 `enable_nvme` 属性值为 `yes` 适用于所有VFC主机设备。
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.显示示例
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. 通过更改为选定适配器启用NVMe/FC协议 `enable_nvme` VFC主机设备属性的值 `yes`。
. 请验证 `FC-NVMe Protocol Device` 已在服务器上创建：
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.示例输出
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. 记录服务器中的主机NQN：
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.显示示例
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.显示示例
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. 检查主机NQN并验证它是否与ONTAP阵列上对应子系统的主机NQN字符串匹配：
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.示例输出
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. 验证启动程序端口是否已启动且正在运行、并且您可以看到目标生命周期。




== 步骤 3：验证 NVMe/FC

验证ONTAP命名空间对于 NVMe/FC 配置是否正确。

.步骤
. 验证ONTAP命名空间是否正确反映在主机上：
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.示例输出
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. （可选）检查多路径状态：
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.显示示例
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== 步骤 4：查看已知问题

带有ONTAP存储的 AIX 的 NVMe/FC 主机配置存在以下已知问题：

[cols="10,30,30"]
|===
| BURT ID (BURT ID) | 标题 | Description 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249."^] | 要修改的AIX NVMe/FC默认APD时间、以支持MCC计划外切换事件 | 默认情况下、AIX操作系统会对NVMe/FC使用全路径关闭(APD)超时值20秒。  但是、ONTAP MetroCluster自动计划外切换(Automatic Undurrated SwitchOver、AUSO)和Tieb破碎 机启动的切换工作流所需时间可能比APD超时窗口要长一些、从而导致I/O错误。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | AIX NVMe/FC将ANATT上限设置为60秒、而不是ONTAP公布的120秒 | ONTAP在控制器标识中显示ANA (非对称命名空间访问)过渡超时为120秒。目前、借助IFIX、AIX会从控制器标识读取ANA过渡超时、但如果超过此限制、则会将其有效地固定到60秒。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | 在AATT到期后、AIX NVMe/FC会命中EIO | 对于任何存储故障转移(Storage Failover、SFO)事件、如果ANA (非对称命名空间访问)过渡超过给定路径上的ANA过渡超时上限、则AIX NVMe/FC主机将失败、并显示I/O错误、尽管命名空间具有备用的运行状况良好的路径。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC等待半/全AATT过期、然后在ANA AEN之后恢复I/O | IBM AIX NVMe/FC不支持ONTAP发布的某些异步通知(Aschron也 会通知、AEN)。这种次优ANA处理方式会导致SFB操作期间性能欠佳。 
|===


== 步骤5：故障排除

在排除任何 NVMe/FC 故障之前，请验证您正在运行的配置是否符合link:https://mysupport.netapp.com/matrix/["IMT"^]规格。如果问题仍然存在，请联系link:https://mysupport.netapp.com["NetApp 支持"^]。
