---
sidebar: sidebar 
permalink: nvme-proxmox-ve-9x.html 
keywords: nvme, proxmox, enterprise 
summary: 如何为 Proxmox VE 9.0 配置 NVMe-oF 主机和ONTAP存储 
---
= 配置 Proxmox VE 9.0 以支持 NVMe-oF 和ONTAP存储
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proxmox VE 9.0 主机支持基于光纤通道的 NVMe (NVMe/FC) 和基于 TCP 的 NVMe (NVMe/TCP) 协议，并支持非对称命名空间访问 (ANA)。ANA 提供与 iSCSI 和 FCP 环境中的非对称逻辑单元访问 (ALUA) 等效的多路径功能。

了解如何为 Proxmox VE 9.0 配置 NVMe over Fabrics (NVMe-oF) 主机。如需更多支持和功能信息，请参阅 link:nvme-proxmox-supported-features.html["ONTAP支持和功能"^]。

NVMe-oF 与 Proxmox VE 9.0 存在以下已知限制：

* 不支持 NVMe-FC 的 SAN 启动配置。




== 步骤 1：验证软件版本和 NVMe 配置

要为 NVMe-oF 配置主机，您应该安装主机和 NVMe 软件包，启用多路径，并验证主机 NQN 配置。

.步骤
. 在服务器上安装 Proxmox VE 9.0。安装完成后，请确认您运行的是所需的 Proxmox VE 9.0 内核：
+
[source, cli]
----
uname -r
----
+
Proxmox VE 9.0 内核版本示例：

+
[listing]
----
6.14.8-2-pve
----
. 安装 `NVMe-CLI` 软件包：
+
[source, cli]
----
apt list|grep nvme-cli
----
+
下面的例子展示了 `nvme-cli`软件包版本：

+
[listing]
----
nvme-cli/stable,now 2.13-2 amd64
----
. 安装 `libnvme` 软件包：
+
[source, cli]
----
apt list|grep libnvme
----
+
下面的例子展示了 `libnvme`软件包版本：

+
[listing]
----
libnvme-dev/stable 1.13-2 amd64
----
. 在主机上，检查 hostnqn 字符串 `/etc/nvme/hostnqn` ：
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
下面的例子展示了 `hostnqn`价值：

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
----
. 验证是否已 `hostnqn` 字符串与匹配 `hostnqn` ONTAP 阵列上对应子系统的字符串：
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_proxmox_FC_NVMeFC
----
+
.显示示例
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  -----------------------------------------------
vs_proxmox_FC_NVMeFC
        sub_176
                  regular   nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a4834
                  regular   nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
2 entries were displayed
----
====
+

NOTE: 如果 `hostnqn`字符串不匹配，请使用 `vserver modify`命令来更新 `hostnqn`相应ONTAP存储系统子系统上的字符串以匹配 `hostnqn`字符串来自 `/etc/nvme/hostnqn`在主机上。





== 步骤 2：配置 NVMe/FC 和 NVMe/TCP

使用 Broadcom/Emulex 或 Marvell/QLogic 适配器配置 NVMe/FC，或使用手动发现和连接操作配置 NVMe/TCP。

.步骤
[role="tabbed-block"]
====
.NVMe/FC - 博通/Emulex
--
为Broadcom/Emulex适配器配置NVMe/FC。

. 验证您使用的适配器型号是否受支持：
+
.. 显示模型名称：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
您应看到以下输出：

+
[listing]
----
SN1700E2P
SN1700E2P
----
.. 显示模型描述：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
您应该看到类似于以下示例的输出：

+
[listing]
----
HPE SN1700E 64Gb 2p FC HBA
HPE SN1700E 64Gb 2p FC HBA
----


. 确认您使用的是建议的Broadcom `lpfc` 固件和内置驱动程序：
+
.. 显示固件版本：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
该命令返回固件版本：

+
[listing]
----
14.4.473.14, sli-4:6:d
14.4.473.14, sli-4:6:d
----
.. 显示收件箱驱动程序版本：
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
以下示例显示了驱动程序版本：

+
[listing]
----
0:14.4.0.7
----


+
有关支持的适配器驱动程序和固件版本的最新列表，请参见link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]。

. 请验证 `lpfc_enable_fc4_type` 设置为 `3`：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. 验证是否可以查看启动程序端口：
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
您应该看到类似以下内容的输出：

+
[listing]
----
0x10005ced8c531948
0x10005ced8c531949
----
. 验证启动程序端口是否联机：
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
您应看到以下输出：

+
[listing]
----
Online
Online
----
. 验证NVMe/FC启动程序端口是否已启用且目标端口是否可见：
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10005ced8c531948 WWNN x20005ced8c531948 DID x082400 *ONLINE*
NVME RPORT       WWPN x200ed039eac79573 WWNN x200dd039eac79573 DID x060902 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2001d039eac79573 WWNN x2000d039eac79573 DID x060904 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000034 Cmpl 0000000034 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000142cfb Issue 0000000000142cfc OutIO 0000000000000001
        abort 00000005 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000005 Err 00000005

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10005ced8c531949 WWNN x20005ced8c531949 DID x082500 *ONLINE*
NVME RPORT       WWPN x2010d039eac79573 WWNN x200dd039eac79573 DID x062902 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2007d039eac79573 WWNN x2000d039eac79573 DID x062904 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000034 Cmpl 0000000034 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000d39f1 Issue 00000000000d39f2 OutIO 0000000000000001
        abort 00000005 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000005 Err 00000005
----
=====


--
.NVMe/FC - Marvell/QLogic
--
为Marvell/QLogic适配器配置NVMe/FC。

. 验证您使用的适配器驱动程序和固件版本是否受支持：
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
以下示例显示了驱动程序和固件版本：

+
[listing]
----
SN1700Q FW:v9.15.05 DVR:v10.02.09.400-k
SN1700Q FW:v9.15.05 DVR:v10.02.09.400-k
----
. 请验证 `ql2xnvmeenable` 已设置。这样、Marvell适配器便可用作NVMe/FC启动程序：
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
预期输出为1。



--
.NVMe/TCP
--
NVMe/TCP 协议不支持自动连接操作。相反，您可以通过执行 NVMe/TCP 来发现 NVMe/TCP 子系统和命名空间 `connect`或者 `connect-all`手动操作。

. 检查启动器端口是否可以跨支持的 NVMe/TCP LIF 获取发现日志页面数据：
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.165.72 -a 192.168.165.51
Discovery Log Number of Records 4, Generation counter 47
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:discovery
traddr:  192.168.165.51
eflags:  *explicit discovery connections*, *duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:discovery
traddr:  192.168.166.50
eflags:  *explicit discovery connections*, *duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:subsystem.sub_176
traddr:  192.168.165.51
eflags:  none
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:subsystem.sub_176
traddr:  192.168.166.50
eflags:  none
sectype: none
----
=====
. 运行 `nvme connect-all` 在节点中所有受支持的NVMe/TCP启动程序-目标SIP上运行命令：
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme connect-all -t tcp -w 192.168.166.73 -a 192.168.166.50
nvme connect-all -t tcp -w 192.168.166.73 -a 192.168.166.51
nvme connect-all -t tcp -w 192.168.165.73 -a 192.168.165.50
nvme connect-all -t tcp -w 192.168.165.73 -a 192.168.165.51
----
=====


[NOTE]
====
NVMe/TCP 的设置 `ctrl_loss_tmo timeout`自动设置为“关闭”。因此：

* 重试次数没有限制（无限重试）。
* 您不需要手动配置特定的 `ctrl_loss_tmo timeout`使用时长 `nvme connect`或者 `nvme connect-all`命令（选项 -l ）。
* 如果发生路径故障，NVMe/TCP 控制器不会超时，并且会无限期地保持连接。


====
--
====


== 步骤 3：可选，启用 NVMe/FC 的 1MB I/O。

ONTAP在识别控制器数据中报告最大数据传输大小 (MDTS) 为 8。这意味着最大 I/O 请求大小可达 1MB。要向 Broadcom NVMe/FC 主机发出 1MB 大小的 I/O 请求，您应该增加 `lpfc`的价值 `lpfc_sg_seg_cnt`参数从默认值 64 更改为 256。


NOTE: 这些步骤不适用于逻辑NVMe/FC主机。

.步骤
. 将 `lpfc_sg_seg_cnt`参数设置为256：
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
您应该会看到类似于以下示例的输出：

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. 运行 `dracut -f`命令并重新启动主机。
. 验证的值是否 `lpfc_sg_seg_cnt`为256：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== 步骤 4：验证 NVMe 启动服务

这 `nvmefc-boot-connections.service`和 `nvmf-autoconnect.service`NVMe/FC 中包含的启动服务 `nvme-cli`系统启动时，软件包会自动启用。

启动完成后，验证 `nvmefc-boot-connections.service`和 `nvmf-autoconnect.service`启动服务已启用。

.步骤
. 验证是否 `nvmf-autoconnect.service`已启用：
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.显示示例输出
[%collapsible]
====
[listing]
----
○ nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2025-10-16 18:00:39 IST; 6 days ago
 Invocation: e146e0b2c339432aad6e0555a528872c
    Process: 1787 ExecStart=/usr/sbin/nvme connect-all --context=autoconnect (code=exited, status=0/SUCCESS)
   Main PID: 1787 (code=exited, status=0/SUCCESS)
   Mem peak: 2.4M
        CPU: 12ms
Oct 16 18:00:39 HPE-DL365-14-176 systemd[1]: Starting nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot...
Oct 16 18:00:39 HPE-DL365-14-176 systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Oct 16 18:00:39 HPE-DL365-14-176 systemd[1]: Finished nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot.
----
====
. 验证是否 `nvmefc-boot-connections.service`已启用：
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.显示示例输出
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2025-10-16 18:00:35 IST; 6 days ago
 Invocation: acf73ac1ef7a402198d6ecc4d075fab0
    Process: 1173 ExecStart=/bin/sh -c echo add > /sys/class/fc/fc_udev_device/nvme_discovery (code=exited, status=0/SUCCESS)
   Main PID: 1173 (code=exited, status=0/SUCCESS)
   Mem peak: 2.1M
        CPU: 11ms

Oct 16 18:00:35 HPE-DL365-14-176 systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Oct 16 18:00:35 HPE-DL365-14-176 systemd[1]: Finished nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== 步骤 5：验证多路径配置

验证内核NVMe多路径状态、ANA状态和ONTAP命名空间是否适用于NVMe-oF配置。

.步骤
. 验证是否已启用内核NVMe多路径：
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
您应看到以下输出：

+
[listing]
----
Y
----
. 验证主机上是否正确显示了ONTAP命名空间的相应 NVMe-oF 设置（例如，将型号设置为NetApp ONTAP Controller，并将负载均衡 iopolicy 设置为 round-robin）：
+
.. 显示子系统：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
您应看到以下输出：

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. 显示策略：
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
您应看到以下输出：

+
[listing]
----
queue-depth
queue-depth
----


. 验证是否已在主机上创建并正确发现命名空间：
+
[source, cli]
----
nvme list
----
+
.显示示例
[%collapsible]
====
[listing]
----
Node          Generic     SN                   Model                    Namespace  Usage                      Format           FW Rev
------------- ----------- -------------------- ------------------------ ---------- -------------------------- ---------------- --------
/dev/nvme2n1  /dev/ng2n1  81PqYFYq2aVAAAAAAAAB NetApp ONTAP Controller   0x1         17.88  GB / 171.80  GB      4 KiB +  0 B   9.17.1
----
====
. 验证每个路径的控制器状态是否为活动状态且是否具有正确的ANA状态：
+
[role="tabbed-block"]
====
.NVMe/FC
--
[source, cli]
----
nvme list-subsys /dev/nvme3n9
----
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys3 - NQN=nqn.1992-08.com.netapp:sn.94929fdb84eb11f0b624d039eac809ba:subsystem.sub_176
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
\
 +- nvme1 *fc* traddr=nn-0x200dd039eac79573:pn-0x2010d039eac79573,host_traddr=nn-0x20005ced8c531949:pn-0x10005ced8c531949 *live optimized*
 +- nvme3 *fc* traddr=nn-0x200dd039eac79573:pn-0x200ed039eac79573,host_traddr=nn-0x20005ced8c531948:pn-0x10005ced8c531948 *live optimized*
+- nvme5 *fc* traddr=nn-0x200dd039eac79573:pn-0x200fd039eac79573,host_traddr=nn-0x20005ced8c531949:pn-0x10005ced8c531949 *live non-optimized*
 +- nvme7 *fc* traddr=nn-0x200dd039eac79573:pn-0x2011d039eac79573,host_traddr=nn-0x20005ced8c531948:pn-0x10005ced8c531948 *live non-optimized*
----
=====
--
.NVMe/TCP
--
[source, cli]
----
nvme list-subsys /dev/nvme2n3
----
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys2 - NQN=nqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:subsystem.sub_176
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:39333550-3333-4753-4844-32594d4a524c
\
 +- nvme2 *tcp* traddr=192.168.166.50,trsvcid=4420,host_traddr=192.168.166.73,src_addr=192.168.166.73 *live optimized*
 +- nvme4 *tcp* traddr=192.168.165.51,trsvcid=4420,host_traddr=192.168.165.73,src_addr=192.168.165.73 *live optimized*
+- nvme6 *tcp* traddr=192.168.166.51,trsvcid=4420,host_traddr=192.168.166.73,src_addr=192.168.166.73 *live non-optimized*
 +- nvme8 *tcp* traddr=192.168.165.50,trsvcid=4420,host_traddr=192.168.165.73,src_addr=192.168.165.73 *live non-optimized*
----
=====
--
====
. 验证NetApp插件是否为每个ONTAP 命名空间设备显示正确的值：
+
[role="tabbed-block"]
====
.列
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----

Device        Vserver               Namespace Path
------------- --------------------- ------------------------------
/dev/nvme2n9  vs_proxmox_FC_NVMeFC  /vol/vol_180_data_nvmefc4/ns

NSID       UUID                            Size
---- ------------------------------------  --------
1    e3d3d544-de8b-4787-93af-bfec7769e909  32.21GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.显示示例
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
      "Device":"/dev/nvme2n9",
      "Vserver":"vs_proxmox_FC_NVMeFC",
      "Subsystem":"sub_176",
      "Namespace_Path":"/vol/vol_180_data_nvmefc4/ns",
      "NSID":9,
      "UUID":"e3d3d544-de8b-4787-93af-bfec7769e909",
      "LBA_Size":4096,
      "Namespace_Size":32212254720,
      "UsedBytes":67899392,
      "Version":"9.17.1"
    }
  ]
----
=====
--
====




== 第6步：查看已知问题

没有已知问题。
