= 
:allow-uri-read: 


要确保为主机正确配置了多路径、请验证是否已定义此 `/etc/multipath.conf`文件、以及是否已为ONTAP LUN配置了NetApp建议的设置。

.步骤
. 验证文件是否 `/etc/multipath.conf`退出。如果此文件不存在、请创建一个空的零字节文件：
+
[source, cli]
----
touch /etc/multipath.conf
----
. 首次创建文件时 `multipath.conf`、您可能需要启用并启动多路径服务以加载建议的设置：
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. 每次启动主机时、空的 `/etc/multipath.conf`零字节文件都会自动加载NetApp建议的主机多路径参数作为默认设置。您无需更改 `/etc/multipath.conf`主机的文件、因为操作系统使用可正确识别和管理ONTAP LUN的多路径参数进行编译。
+
下表显示了ONTAP LUN的Linux操作系统本机编译多路径参数设置。

+
.显示参数设置
[%collapsible]
====
[cols="2"]
|===
| 参数 | 正在设置 ... 


| detect_prio | 是的。 


| dev_los_TMO | " 无限 " 


| 故障恢复 | 即时 


| fast_io_fail_sMO | 5. 


| features | "2 pG_INIT_retries 50" 


| flush_on_last_del | “总是” 


| 硬件处理程序 | “1” 


| no_path_retry | 队列 


| path_checker | "TUR" 


| path_grouping_policy | "Group_by-prio" 


| path_selector | " 服务时间 0" 


| Polling interval | 5. 


| PRIO | ONTAP 


| 产品 | LUN 


| Retain Attached Hw_handler | 是的。 


| rr_weight | " 统一 " 


| user_friendly_names | 否 


| 供应商 | NetApp 
|===
====
. （可选）覆盖默认值 `find_multipaths`用于确保 multipathd 正确发现和管理ONTAP LUN 的参数：
+
--
.. 放 `find_multipaths`在默认值部分设置为“否” `/etc/multipath.conf` ：
+
[source, cli]
----
defaults {
    find_multipaths "no"
}
----
.. 重新加载多路径服务：
+
[source, cli]
----
systemctl reload multipathd
----


--
+

NOTE: 默认情况下，Proxmox OS 原生多路径配置集 `find_multipaths`设置为“*严格*”，并带有空零字节 `/etc/multipath.conf`每次启动主机时都会运行配置文件。这可以防止主机发现新出现的ONTAP LUN 作为多路径设备，这意味着它们不会自动出现在多路径控制之下。每次重启后，现有的ONTAP LUN 仍保持被发现状态并处于多路径控制之下。

. 验证ONTAP LUN的参数设置和路径状态：
+
[source, cli]
----
multipath -ll
----
+
默认多路径参数支持ASA、AFF和FAS配置。在这些配置中、一个ONTAP LUN不应需要超过四个路径。如果路径数超过四个、则可能会在存储故障期间导致路径出现问题。

+
以下示例输出显示了ASA、AFF或FAS配置中ONTAP LUN的正确参数设置和路径状态。

+
[role="tabbed-block"]
====
.ASA配置
--
ASA配置可优化指向给定LUN的所有路径、使其保持活动状态。这样可以同时通过所有路径提供I/O操作、从而提高性能。

.显示示例
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038315071592b59713261566d dm-38 NETAPP,LUN C-Mode
size=100G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 8:0:0:7 sdbv 68:144 active ready running
  |- 9:0:0:7 sdbx 68:176 active ready running
  |- 6:0:0:7 sdbr 68:80  active ready running
  `- 7:0:0:7 sdbt 68:112 active ready running

----
=====
--
.AFF或FAS配置
--
AFF或FAS配置应具有两组优先级较高和较低的路径。优先级较高的主动/优化路径由聚合所在的控制器提供。优先级较低的路径处于活动状态、但未进行优化、因为它们由其他控制器提供服务。只有在优化路径不可用时、才会使用非优化路径。

以下示例显示了具有两条活动/优化路径和两条活动/非优化路径的ONTAP LUN 的输出：

.显示示例
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383149764b5d567257516273 dm-0 NETAPP,LUN C-Mode
size=150G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:3:0  sdcg 69:64  active ready running
| `- 10:0:0:0  sdb  8:16   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:0  sdc  8:32   active ready running
  `- 16:0:2:0  sdcf 69:48  active ready running
----
=====
--
====

